### ISSUE TITLE
Problems with running on Windows 7

### ISSUE THREAD

**Issue by MaxSm** [micahflee/onionshare#101]
The program eventually responds when Tor is not engaged, asking to run it. Though after Tor browser is switched on and .exe is activated, nothing happens.
The program is installed via the file downloaded from the source. Then the installer is being executed. Installation finishes with no reports of error of any kind.

**Comment by umbrageous** [comment]
I installed OnionShare via installer at onionshare.org. Win 7 Pro. Tor Browser Bundle 5.0.4. I started Tor first. Hitting "Start sharing" causes Tor to crash. After restart of Tor as invited, OnionShare hangs, yellow dot, "Starting Tor hidden server...".

Any thoughts?

**Comment by micahflee** [comment]
That shouldn't be happening, but I'll look into it and try to reproduce it.

**Comment by micahflee** [comment]
I can't reproduce it. I just made a fresh install of Windows 7 Pro, installed Tor Browser 5.0.4, and OnionShare 0.7.1, and it all seems to work.

This issue is vaguely reminiscent of #179. Basically, OnionShare is talking to the Tor process that's included in Tor Browser and when it tells it to start the hidden service, Tor freaks out and crashes. In Windows, OnionShare tries writing the hidden service directory to `%TEMP%\onionshare`, and if Tor doesn't have permission to write to here I can see that being the cause of the crash.

But this issue should completely go away in the (soon-to-be-released) next version of OnionShare, if you're using Tor Browser 5.5x (the current alpha) because it will use ephemeral hidden services and will no longer need to write to the filesystem. So I think it's a better use of time to just finish releasing the next version rather than trying to figure out how to reproduce the crash.
