### ISSUE TITLE
Not require TOR Browser

### ISSUE THREAD

**Issue by trymeouteh** [micahflee/onionshare#1042]
Please add the TOR dependencies into onionshare and not have it requite you to install the TOR Browser in order for onionshare to fully work. I am not suggestion to remove TOR from the project since it is based on TOR but to not require the TOR browser to be present on the computer for onionshare to work.

**Comment by mig5** [comment]
(It's Tor, not TOR)

OnionShare doesn't require Tor Browser installed to work. On Mac or Windows It comes bundled with the Tor binary, and on Mac, Windows and Linux it can use the system-installed Tor. 

Whilst it *can* use the Tor Browser's tor, it doesn't even default to that mode, you have to set it in the Settings if you want that.

Not sure where you're getting OnionShare from but this is the second issue you've raised today that suggests you've not actually tried OnionShare since you're asking for things that already exist (auto-stop timer for example, and this one).
