### ISSUE TITLE
Website mode issues with folders

### ISSUE THREAD

**Issue by cdokolas** [micahflee/onionshare#1053]
There seems to be some confusion (for lack of a better word) for folders in the list under "Publish Website".

After some testing:
* If a single folder is present in the list (i.e. the only one added), the contents of the folder are served. Contents of sub-folders generate 404s.
* If only files are present in the list they appear in a directory listing and load as root sub-resources (is this the right definition?)
* When the contents of the list are mixed (i.e. at least two items and at least one is a folder), I get a 500 error page for the root in the browser (actual response content) although the history panel shows a 200. I also get a 404 for any html content in any of the two folders.

All this suggests that only two cases are workable (undocumented behavior?):
1. Add only files: they will be server under the root (if an `index.html` is present, it will also be the default content)
1. Add only one folder: only the files in it will be served (sub-folders are *not accessible*)

**Comment by mig5** [comment]
Hi,

Thanks for the report.

>     * If a single folder is present in the list (i.e. the only one added), the contents of the folder are served. Contents of sub-folders generate 404s.

This sounds like a bug, we probably didn't test subfolders of other folders.

> 
>     * If only files are present in the list they appear in a directory listing and load as root sub-resources (is this the right definition?)

That is correct and by design. In the absence of an index.html, a directory listing is shown instead.

> 
>     * When the contents of the list are mixed (i.e. at least two items and at least one is a folder), I get a 500 error page for the root in the browser (actual response content) although the history panel shows a 200. I also get a 404 for any html content in any of the two folders.

This sounds like a bug - I've not quite understood what you're saying, but will test it! You're saying that if you share a folder alongside some other arbitrary filename in the root, instead of a directory listing at the root, you get a 500? Isn't this contradicting what you saw in your second dot point?

I'll mark this as a bug and we'll look into it and hopefully fix it in a point release soon. Thanks!

**Comment by cdokolas** [comment]
A big thanks for your response.

Regarding the third case, it's different than the second in that the second only has files in the list (UI), while in the third, there is a folder as well (not nested). Let me illustrate:

Second case:
![image](https://user-images.githubusercontent.com/1136790/66986575-d7220580-f0c7-11e9-970e-b041903dd1f2.png)
![image](https://user-images.githubusercontent.com/1136790/66986592-e012d700-f0c7-11e9-981a-74f43e8ad136.png)

Third case:
![image](https://user-images.githubusercontent.com/1136790/66986739-20725500-f0c8-11e9-9bb8-ee4decbc0c27.png)
![image](https://user-images.githubusercontent.com/1136790/66986758-2831f980-f0c8-11e9-9abf-cb19764b7a8b.png)

**Comment by mig5** [comment]
Try as I might, I can't reproduce that last issue with the Internal Server 500 error. I can share a folder and a .html file without any problem.

Can you run OnionShare from the command line with `onionshare-gui --verbose` and try the third scenario again? The Internal Server Error should throw a big Python stacktrace to the console, which will be useful to debug.

I wonder what those arrows mean on the 'site1' folder. If it's a symlink, I tried sharing a symlink to a folder too, but it worked for me...

If the data you are sharing is not super sensitive, or if you are able to reproduce it with 'dummy' files, maybe it would be useful to get a copy of those in order to try and reproduce with the same files.

**Comment by cdokolas** [comment]
I will try the `--verbose` thing ASAP.

Meanwhile, I forgot to mention I'm running a Windows 10 x64 system. The "arrows" decoration on the icon just means that the file/folder is filesystem-compressed.

**Comment by cdokolas** [comment]
Hmm... the `onionshare-gui --verbose` command spawns a separate process :(

Is there a log?

**Comment by cdokolas** [comment]
Found a `flask.log` file with this repeating block:

```
Exception on / [GET]
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 2446, in wsgi_app
  File "site-packages\flask\app.py", line 1951, in full_dispatch_request
  File "site-packages\flask\app.py", line 1820, in handle_user_exception
  File "site-packages\flask\_compat.py", line 39, in reraise
  File "site-packages\flask\app.py", line 1949, in full_dispatch_request
  File "site-packages\flask\app.py", line 1935, in dispatch_request
  File "onionshare\web\website_mode.py", line 27, in path_public
  File "onionshare\web\website_mode.py", line 33, in path_logic
  File "onionshare\web\website_mode.py", line 98, in render_logic
  File "onionshare\web\send_base_mode.py", line 111, in directory_listing
  File "onionshare\web\send_base_mode.py", line 125, in build_directory_listing
KeyError: 'site1/'
```
On a different note, I've monitored the process and I see it loading the 404 template and sending something over TCP. Could it be something on the TOR network? Also, the 500 page seems faked by the TOR browser to me.

**Comment by micahflee** [comment]
Over a year later and I'm finally looking at this.

Like @mig5 I also can't reproduce the error 500 issue. The code has changed so much at this point that I think I can just assume that it's no longer an issue.

And after looking at this issue in detail, I think the problem doesn't actually have anything to do with the difference between starting a website service with a single folder vs. with multiple files. I actually think that works as intended (if you start the service with a single folder, it treats it as if you started the service with the contents of that folder).

Instead, I think the problem has to do with trailing slashes. Let's say you start a website with these files:

- `images` (directory)
- `foo.html`

Under the hood, onionshare treats the only valid URLs as:

- `/images/` (with at trailing slash)
- `foo.html`

And if you load `/images` (without a trailing slash) it responds with a 404. So the solution is to make directory listing work with or without trailing slashes, and all the 404s will go away.

**Comment by 1000i100** [comment]
I just test to host my static website https://1forma-tic.fr/ with onionshare. index.html load as of other root file, but all img/files don't load and display 404 error (i've tried from windows10x64)

**Comment by efialtos** [comment]
Error 500 occurs when I drag-n-drop a file or a directory into fileshare or webserver filelist, and at least one of the files or directories is placed outside the snap permissions or contains a softlink pointing to anywhere outside it.

```
root# snap interfaces onionshare
Slot                             Plug
gnome-3-34-1804:gnome-3-34-1804  onionshare
gtk-common-themes:gtk-3-themes   onionshare
gtk-common-themes:icon-themes    onionshare
gtk-common-themes:sound-themes   onionshare
:desktop                         onionshare
:desktop-legacy                  onionshare
:gsettings                       onionshare
:home                            onionshare
:network                         onionshare
:network-bind                    onionshare
:opengl                          onionshare
:wayland                         onionshare
:x11                             onionshare

```
Thus the only user-available fileshare or website **must** be inside /home. Frustrating, isn't it?

If instead of dragging I use the button 'Add', and browse the folders, it  doesn't access the folders content except /home showing them empty. Anyway it allows to choose any folder in the disk root, resulting error 500 again.
