### ISSUE TITLE
[Feature Reguest] Option for Content Security Policy header

### ISSUE THREAD

**Issue by seafox** [micahflee/onionshare#1058]
When enabled, currently CSP header is too strict as it disables all CSS functionality, even embedded in html file. That significantly affects pages/site looks. Please add less strict option to restore CSS functionality without enabling JS stuff.

**Comment by mig5** [comment]
Hi,

Yes, for this reason we allow to disable the CSP when using website mode to avoid such issues.

Under Settings -> Website settings you can check the box 'Disable Content Security Policy header'. See [this page in the documentation](https://github.com/micahflee/onionshare/wiki/Content-Security-Policy).

We made the decision not to allow setting any custom CSP because it will make the Settings too complicated for most users. So for now it remains either 'leave it on' or 'turn it off' but nothing in between.

Thanks for using OnionShare!

**Comment by mig5** [comment]
> even embedded in html file

Note that 'inline' CSS/JS is [not recommended](https://developers.google.com/web/fundamentals/security/csp#inline_code_is_considered_harmful) - the CSP header allows `style-src: self` so you could still load separate css files relative to the site root with the default CSP.

**Comment by seafox** [comment]
I see.
```
 r.headers.set(
                "Content-Security-Policy",
                "default-src 'self'; style-src 'self'; script-src 'self'; img-src 'self' data:;",
            )
```
Thanks for the link and completely agree, inline CSS isn't safe nor clean to code.
Anyway, a custom CSP header would make sense. Especially when you are allowing it to be completely disabled! For instance, one might have more strict requirement than currently is to entirely disable JS on his static site. That'd be reasonable IMHO.
