### ISSUE TITLE
connect to TOR using version built into Onionshare gets stuck

### ISSUE THREAD

**Issue by eastavin** [micahflee/onionshare#1066]
Why does connecting using the Tor version built into Onionshare 2.2 always get stuck at 85-95% and never connect?  I have beating a dead horse for an hour now and it wont connect using this easy method.

There is no problem connecting the TOR browser itself to the tor network... so why does the built in version in Onionshare fail to work?  The onionshare website said this was supposed to be easy to use? Having to reconfigure and start multiple packages to get it to work is not easy says my better half :)

**Comment by mig5** [comment]
If OnionShare is hanging connecting to Tor, that's an issue connecting to the Tor network, not an OnionShare specific issue. This can happen from time to time on the Tor network for various reasons, but it's not OnionShare causing it.

Your Tor Browser might have a faster experience connecting to Tor because it retains cache data that persists across restarts. OnionShare does not.

You could try opening the Settings in OnionShare, and choose the option 'Attempt auto-configuration with Tor Browser' (instead of 'Use the Tor version built into OnionShare' which is the default mode). You have to keep Tor Browser running in the background to use this option, but it will probably make your OnionShare connect instantly.

**Comment by eastavin** [comment]
Hello.  You appear to misinterpret my email.  I explained that Tor works
fine.. however when we allow Onionshare to log in to the network using the
built in interface it hangs.  If I switch to using the Tor Browser ..
seconds later... Onionshare logs into Tor without any difficulty...  So
clearly there is NO problem with TOR but the problem is with teh ONIONSHARE
built in connection code.

Now as you appear to not understand.. If I disconnect and switch back to
the built in onionshare method... it hangs... then if I immediately switch
to Tor browser it logs into the network OK again.  So I can do this all day
with the same result... again the issue is clearly onionshares built in
implementation of the tor network.

So the point of all this is to advise you that the built in method in
Onionshare does not work.  I thought you would be interested in this so you
might look into what needs to be fixed.

Hope I helped.
