### ISSUE TITLE
Receive Mode does not show ETA/upload size in progress bars

### ISSUE THREAD

**Issue by lrq3000** [micahflee/onionshare#1089]
When sending/receiving large files, or if the connection is particularly bad, it would be nice to have an estimation of transfer speed and the remaining time to transfer the data. This is useful to evaluate how the connection perform, and if the users need to put some countermeasures in place (ie, if the download will take too much time anyway to complete in a reasonable time, exchaging receiver and sender may help if upload and download bandwidths of the internet provider are asymmetrical).

Since the app is in Python, you may be interested in taking a look at [tqdm](https://github.com/tqdm/tqdm), which is a library that is focused on providing easy but precise progress bars. Disclaimer: I was involved with tqdm in the past. (but I'm not advising tqdm to everyone, you can look at my github history, it's just that here I think it could be a good addition in terms of functionality to get estimated download times and with low effort by reusing a library).

**Comment by imstanz** [comment]
Not a bad idea...
Some good suggestions, will really enhance onionshare :)

**Comment by mig5** [comment]
This already exists for downloads (ETA and total downloaded bytes is shown in the progress bar, as seen in the History pane).

Incidentally, this wasn't showing for Receive Mode though (uploads), due to a separate bug. A PR is forthcoming.  I'm going to rename the issue to reflect that, since this definitely exists for 'downloads' already.
