### ISSUE TITLE
[Feature] Making downloading in onionshare be able to continue at anytime

### ISSUE THREAD

**Issue by ShadowSocks12** [micahflee/onionshare#1135]
Hi, I see that sharing through onionshare needs my onionshare runing all the time or the receiver will have to restart downloading.
(that means the receiver and I won't turn our computers off in a short time when I share large files like 10 GB)
so I was thinking that onionshare should be similar to utorrent in an important point,
The important point is, 
you see.....in utorrent, you can continue downloading at anytime even after your turn on your PC again, The download doesn't get corrupted, you don't have to restart the whole download...you can continue at anytime as long as there is someone sharing.

What I mean is I don't want to (((keep my computer on until the receiver is finished receiving, when I share large files))).
I want the receiver to be able to [[[[continue]]]] downloading at anytime he wants -just like in utorrent- as long as I still have the files that I am sending and my onionshare is running. I mean when everytime I open my onionshare he should still be able to continue downloading not to restart the whole download.

I hope you understood what I mean, and sorry for my English.
And Thank You.

**Comment by mig5** [comment]
@ShadowSocks12 thanks for your report. What you are describing is solved by a technical solution known as 'range requests'.

We have an issue for that here: #736 and we have a pull request to try and solve it here: #804, however it requires more work at this time.

I am going to close this just so that discussion and focus can remain in the original issue #736 , please feel free to subscribe to that issue so that you are kept up to date if or when it gets fixed.
