### ISSUE TITLE
GPG key has expired

### ISSUE THREAD

**Issue by Zaczero** [micahflee/onionshare#1148]
https://github.com/micahflee/onionshare/wiki/Verifying-Signatures
The signing key has expired on 5/29/2020 (0x403C2657CD994F73).

**Comment by micahflee** [comment]
The key has been updated, the problem is just that the SKS keyserver network is [broken](https://tech.firstlook.media/the-death-of-sks-pgp-keyservers-and-how-first-look-media-is-handling-it) and my key has been spammed with so many fake signatures it can't be imported.

I just updated the wiki page with new places to get my current key.
