### ISSUE TITLE
Allow the host to pin tabs after creation

### ISSUE THREAD

**Issue by Scripter17** [micahflee/onionshare#1233]
Every once in a while I send my friends a link and, for whatever reason, have to reboot my computer before they use it  
It'd be nice if I didn't have to either plan ahead or send a new link

I'm not sure how the GUI system that OS uses works, but I imagine right clicking a tab to show a drop down menu with "Pin/unpin tab" (like how web browsers do it) would be a clean solution.

**Comment by mig5** [comment]
Hi @Scripter17 

If you are using the dev release (since you are talking about tabs), click 'Advanced' on the tab and check the box 'Save this tab, and automatically open it when I open OnionShare'.

As well as the tab being preserved, the onion address itself will also be preserved, meaning you can start the same onion after you reboot.

In earlier versions of OnionShare, this same setting was called 'Use a persistent address' and appears in the Settings dialog.

![Screenshot_2020-11-25_10-13-28](https://user-images.githubusercontent.com/99173/100162103-e6989280-2f06-11eb-976b-f9df57210427.png)

**Comment by Scripter17** [comment]
I knew you could do that at the start, but I never noticed you could do it after stopping the service

Thanks!
