### ISSUE TITLE
Traceback on MacOS when opening SettingsDialog cog icon

### ISSUE THREAD

**Issue by mig5** [micahflee/onionshare#1237]
On macOS 10.15.7, either via the 'official' v2.3.dev2 dmg or having built from source via `desktop/README.md`, I get this error when I try to click on the SettingsDialog (cog icon):

```
Traceback (most recent call last):
File "/Applications/OnionShare.app/Contents/Resources/app/onionshare/main_window.py", line 228, in open_settings
d = SettingsDialog(self.common)
File "/Applications/OnionShare.app/Contents/Resources/app/onionshare/settings_dialog.py", line 145, in __init__
) = self.common.get_tor_paths()
File "/Applications/OnionShare.app/Contents/Resources/app_packages/onionshare_cli/common.py", line 98, in get_tor_paths
    prefix = os.path.dirname(os.path.dirname(tor_path))
  File "/Applications/OnionShare.app/Contents/Resources/Support/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I have also been trying to run develop branch via briefcase on Linux, and the SettingsDialog opens, but trying to click on the radio buttons to select Tor modes seems to freeze, or only occasionally 'switch' the active radio button. Not sure if is related or a separate issue yet. That's on Debian 10.

**Comment by micahflee** [comment]
I figured out what the problem is! The reason why I'm not reproducing it on my system is I have a system Tor installed (`brew install tor`) and you don't.

Basically, `onionshare-cli` (which you can install in macOS using `pip3`) finds your `tor` binary using:

```
tor_path = shutil.which("tor")
```

Because it doesn't ship with a copy of tor, it requires that you install it yourself, like using homebrew, to use the CLI.

However the GUI is supposed to look for the tor binary in a different location, inside the app bundle. It looks like the logic to connect to bundled tor when opening OnionShare looks for it in the right place, but the code in the settings dialog looks for it as if it were the CLI, and I just hadn't noticed because I had system tor installed.
