### ISSUE TITLE
Dead link in "How Do I Install Onionshare" wiki page

### ISSUE THREAD

**Issue by xxc3nsoredxx** [micahflee/onionshare#1251]
The link in "Follow [these build instructions](https://github.com/micahflee/onionshare/blob/master/BUILD.md#linux) to install build from the source code" at the bottom of the [How Do I Install Onionshare](https://github.com/micahflee/onionshare/wiki/How-Do-I-Install-Onionshare#other-linux) page leads to a 404. The referenced `BUILD.md` file doesn't exist anymore.

**Comment by whew** [comment]
I would also like to know how to build it since the `dev_scripts` folder doesn't exist anymore.

**Comment by mig5** [comment]
If you want to build the app as it stands in `dev` branch, please follow the README.md inside the `desktop` folder:

https://github.com/micahflee/onionshare/blob/develop/desktop/README.md

You'll see the updated section for running the equivalent 'dev script' in this section:

https://github.com/micahflee/onionshare/blob/develop/desktop/README.md#running-onionshare-from-the-source-code-tree

**Comment by mig5** [comment]
I've updated the wiki page to point to the `BUILD.md` in the `stable` branch (it was pointing to `master` branch which has been renamed to `stable`)

https://github.com/micahflee/onionshare/blob/stable/BUILD.md#linux

The wiki will soon be removed in favor of the yet-to-be-released https://docs.onionshare.org, which will have updated instructions for building from the `develop` branch. 

Much of the wiki reflects the state of the `stable` branch, not what's in `develop`, and it causes confusion because `develop` is the default branch that loads in the Github interface, where our README references docs.onionshare.org, which leads to the next question 'why doesn't that site work' (it's not ready).

In the meantime, the comment above, is how to build `develop` branch at this time if you don't want to use the `stable` release.
