### ISSUE TITLE
Links to instructions to install on non-Ubuntu non-Fedora Linux are broken

### ISSUE THREAD

**Issue by AmkG** [micahflee/onionshare#1267]
On https://onionshare.org the link under "Other Linux" is broken:

> If you are using a different version of Linux, [follow these build instructions](https://github.com/micahflee/onionshare/blob/master/BUILD.md#gnulinux) to install.

In addition, the `README.md` file also includes a broken link to build instructions:

> See [these instructions](https://docs.onionshare.org/en/install.html#install-in-linux-with-flatpak) to install OnionShare in Linux with Flatpak.

Where can I get actual instructions and can these links be fixed?

**Comment by quatrejuin** [comment]
Try https://github.com/micahflee/onionshare/blob/stable/BUILD.md

**Comment by quatrejuin** [comment]
Check https://github.com/micahflee/onionshare/wiki/How-Do-I-Install-Onionshare

**Comment by whew** [comment]
The default branch that github shows is the `develop` branch, which is why in the readme it points to `docs.onionshare.org`. That website is going to replace the wiki eventually but it isn't operational yet. The link on the site should point to https://github.com/micahflee/onionshare/blob/stable/BUILD.md#gnulinux. @mig5 explains this in #1251.

**Comment by mig5** [comment]
All fixed as of the last release and the release of the Documentation site. The 'Linux' section of https://onionshare.org takes you to https://docs.onionshare.org/2.3.1/en/install.html#install-in-linux
