### ISSUE TITLE
Allow optional customizing a title/description for each onion service

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#1306]
Right now all OnionShare services look the same in Tor Browser, like this:

![Screenshot from 2021-02-28 11-37-46](https://user-images.githubusercontent.com/156128/109431054-65dfab80-79b9-11eb-8bd3-4b60389221b9.png)

It would be cool to allow the user to give their service a specific name, so instead of "OnionShare" at the top it could say "Micah's Anonymous Dropbox" or whatever I choose. And likewise, it would be cool to all an HTML field for a description, so that you could basically write some text explaining whatever you want to explain, include links, etc.

If you give a service a custom title, the GUI can use your custom title in the tab bar too (so "Micah's Anonymous Dropbox" instead of "Receive").

**Comment by mig5** [comment]
We have a related issue https://github.com/micahflee/onionshare/issues/865 which evolved to 'allow customization of the page' - I think we could maybe close it since it's so closely related to this one, and because I agree that extending it beyond just Receive mode might be nice.

We should also remember that allowing customization aids in helping the user shoot themselves in the foot: customization makes an onionshare instance more easily identifiable (steganography?) and maybe even helps pinpoint versions (if it was customized, we know the instance is above a certain version) or maybe the user even specifies the version number in the customized theme. Anyway, we can't protect against that unless we don't allow the customization at all - so it would just have to be a documentation thing to consider.
