### ISSUE TITLE
OnionShare and PHP

### ISSUE THREAD

**Issue by jv1337** [micahflee/onionshare#1361]
After a quick test, it appears that OnionShare is not compatible with using PHP, such as the following code that I wrote in an index.php file:
`<?php
     echo "Hello World!";
?>`
Obviously, the rest of the HTML stuff (not shared in code snippet) showed up, but the PHP did not. Also, even when named "index.php" it stilled showed the website directory instead of the index.php page (unlike when listing something as index.html).

Considering I'm wanting to be able to access a database from within my website, my question is, is there a way to make PHP work with OnionShare?

Considering it's _significantly_ easier to get an onion site operational using OnionShare than with other solutions, I'd _prefer_ to have some way to make PHP work while OnionShare.

**Comment by micahflee** [comment]
Unfortunately adding support for PHP, or any server-side language, would be a security nightmare, which is why website mode only supports static websites. If PHP were running on the server it would be able to do things like make HTTP requests without Tor, access any readable files on the disk, etc -- so sharing a vulnerable PHP script could completely break the security of OnionShare.

If we did want to add some sort of backend/database functionality, it would be safer to make like a "blog" mode that lets you edit content within OnionShare, rather than hosting arbitrary code.
