### ISSUE TITLE
sign all git commits

### ISSUE THREAD

**Issue by adrelanos** [micahflee/onionshare#221]
For better security, could you please sign all upcoming git commits?

If required, I can make the case for the usefulness of signing git commits, even if signed git tags are available.

**Comment by micahflee** [comment]
Sure, I'd be interested in the case for signing all git commits (if there's a good blog post on it already that would work too). I mean, it would probably make it less likely that I would accidentally sign a git tag with a malicious commit with my name on it, assuming I verify my own commit sigs before signing a tag.

It would also be inconvenient for me because I compartmentalize my PGP keys away from where I do software development, but I could solve that (or create a software development key, which isn't a bad idea either).

What about commits from other developers that submit pull requests?

**Comment by adrelanos** [comment]
That one is easy to answer. The other ones I need some time researching
the sources again.

Micah Lee:
> What about commits from other developers that submit pull requests?

In that case you just sign the merge commit. Therefore git master will
always be some git commit signed by you, no matter if you merged commits
by other developers.

**Comment by adrelanos** [comment]
This blog post is the best on the topic:
http://mikegerwitz.com/papers/git-horror-story

And then there is also this forum thread where I gone wild by consulting various people and mailing lists. All 
https://forums.whonix.org/t/security-git-general-verification-verifying-whonix-submodules/513/11

**Comment by adrelanos** [comment]
And btw here is Whonix's documentation on gpg verification of git repositories:
https://www.whonix.org/wiki/Dev/Build_Documentation/11_full#Get_the_Signing_Key

**Comment by micahflee** [comment]
Cool, I will look into all of this and try to make a decision. The main reason I'm hesitant is because OnionShare is cross-platform, and I necessarily need to make commits from separate computers running Windows, OSX, and several different Linux VMs, but I don't have access to my key on all of these devices. So having the same secret key available in many different environments, and also on different physical hardware, is a pain if I want to keep that key as secure as possible.

Perhaps I should make a dedicated software development key rather than using the same key I use for email. And I could also put it on a smart card, so I don't need to keep copies of it on different computers, but then I'll need to make sure git/gpg on Windows can sign commits using a key stored on a smart card.

**Comment by adrelanos** [comment]
Micah Lee:
> Cool, I will look into all of this and try to make a decision. The
> main reason I'm hesitant is because OnionShare is cross-platform, and
> I necessarily need to make commits from separate computers running
> Windows, OSX, and several different Linux VMs, but I don't have
> access to my key on all of these devices. So having the same secret
> key available in many different environments, and also on different
> physical hardware, is a pain if I want to keep that key as secure as
> possible.

Okay. I see. Understandable.

> Perhaps I should make a dedicated software development key rather
> than using the same key I use for email.

Up to you. I personally find that confusing when other people do that.

> And I could also put it on a
> smart card, so I don't need to keep copies of it on different
> computers, but then I'll need to make sure git/gpg on Windows can
> sign commits using a key stored on a smart card.

I personally felt better if you never gave any proprietary operating
systems access to your signing keys.

So perhaps consider something else:
Sign all your commits on your Linux machine, where you feel comfortable
having your key.

In between signed tag releases, then one could still get "closer" to the
latest verifiable commit. I would verify your last signed commit, and
then more carefully review the remaining unsigned ones. That would still
be an improvement.

One of the main things here, creating a signed git tag out of a signed
git commit, is the best security improvement here.

[Unless that also would make your work flow too uncomfortable. The least
thing we need is making your work flow so secure but inconvenient, that
you actually stop working. :)]

**Comment by jvoisin** [comment]
I'd like to mention the fact that Linus himself [said]( http://git.661346.n2.nabble.com/GPG-signing-for-git-commit-td2582986.html ) that automatic signing makes not sense.

**Comment by burdges** [comment]
It'd be wonderful if git were designed to meet modern notions cryptographic security, including something stronger than SHA1.  I donno if git's data structures and transport operations have been much reviewed by cryptographers though.  

Almost everyone thinks a 256 bit SHA2 or SHA3 should provide 128 bits of post-quantum security, so that suffices for any foreseeable future.  I suppose someone could write a tool that embedded one of those into git's data structures or even commit messages.  

As an aside, I noticed a funny way to get 128 bits of post-quantum security from a 128 bit hash:  Just use a memory hard hash function like Argon2.  It's not as secure as using a good 256 bits hash technically.  Ain't much chance anyone will build a quantum computer with billions of qubits needed to apply Grover's algorithm to Argon2 though.  lol 

Anyways if you're worried about this then look around for cryptographic attacks on the git protocol, as that'll give you a good idea of the actual threats.  I'd expect they exist but mostly too easy to detect to be a realistic threat.

**Comment by nbraud** [comment]
@burdges FYI, Git's history is a form of [Merkle tree](https://en.wikipedia.org/wiki/Merkle_tree), so signing a commit /does/ make the history up to that point unforgeable (by an attacker that cannot forge a signature, and cannot solve a preimage problem for the hash function).

Regarding the use of memory-hard functions for “post-quantumness”, I doubt this is the place to start suggesting homebrewed crypto (esp. with security claims such as “technically not 256-bits of security”).

**Comment by nbraud** [comment]
@micahflee Regarding signing Git commits while working with many people and machines, here is a workflow that I've enjoyed quite a bit of success with:
- work as usual, don't autocommit;
- submit all changes to the repo as a pull request, the same way an external contributor would;
- review the change and perform a signed merge into `master`, from a trusted computer.

Rationale:
- does not require the proliferation of your private keys;
- the tip of the main branch is signed at all times, so people can fetch/clone it and have strong guarantees this is the code you approved of;
- this ties (by convention) code-review and code-signing: you don't have the issue outlined in the [git horror story](http://mikegerwitz.com/papers/git-horror-story) because by signing a merge, you attest you reviewed the commits that got added since the last signature.

**Comment by micahflee** [comment]
I think this makes sense. I've been signing my git commits by default lately, ever since I discovered I could my my `~/.gitconfig` look like this:

```
[user]
    name = Micah Lee
    email = micah@micahflee.com
    signingkey = 927F419D7EC82C2F149C1BD1403C2657CD994F73

[gpg]
    program = qubes-gpg-client-wrapper

[commit]
    gpgsign = true
```

So I will strive to sign all commits. And if I write code on, for example, a Windows computer to implement and test Windows functionality, I'll do what @nbraud suggests and include all my commits in a PR, that I'll review and merge with a signed commit on a more trusted machine.

**Comment by nbraud** [comment]
@micahflee Awesome, thanks.

**Comment by nbraud** [comment]
@micahflee By the way, a caveat I forgot to mention is that `git merge`'s `-S` flag is ineffective if the merge is fast-forward.
The reliable way to make a signed merge is `git merge --no-ff -S`.
