### ISSUE TITLE
Onionshare 0.8 doesn't can't connect to HS on Jessie

### ISSUE THREAD

**Issue by freddymartinez9** [micahflee/onionshare#232]
Hi Micah,

I recently installed 0.8 on two different machines running jessie and onionshare seems to have a regression setting up the HS, I am running TBB 5.0.4 (the latest stable) and 0.8. 

Here is the stacktrace

```
Connecting to Tor control port to set up hidden service on port 48201.
Traceback (most recent call last):
  File "/usr/bin/onionshare", line 29, in <module>
    onionshare.main()
  File "/usr/lib/python2.7/dist-packages/onionshare/onionshare.py", line 137, in main
    app.start_hidden_service()
  File "/usr/lib/python2.7/dist-packages/onionshare/onionshare.py", line 75, in start_hidden_service
    self.onion_host = self.hs.start(self.port)
  File "/usr/lib/python2.7/dist-packages/onionshare/hs.py", line 114, in start
    hs_conf = self.c.get_hidden_service_conf()
AttributeError: 'Controller' object has no attribute 'get_hidden_service_conf'
```

Furthermore, what's strange is if I run it again, I get the same error on a different port (I was under the impression Onionshare was expecting 9050 or something like that 

```
Connecting to Tor control port to set up hidden service on port 33986.
```

**Comment by micahflee** [comment]
Thanks for reporting this.

The port number that's changing on you is the onionshare web app port, which is random each time you start a new onionshare service. The Tor control port is 9151 for Tor Browser, 9153 for Tor Messenger, and 9051 for system Tor, so it tries connecting to them in that order.

It looks like you successfully connected to the control port, but the error is thrown because the Controller object doesn't have a `get_hidden_service_conf`. Eek, I think that that method is only available in new versions of stem (the Tor control port library I'm using), and probably jessie doesn't come with a new enough version. Oops, I think the jessie I was testing in I installed python-stem from sid, so I could test ephemeral stuff.

**Comment by freddymartinez9** [comment]
Hi Micah 

Yea that is the problem, as a temporary workaround I did a pip upgrade to the latest step  (stem 1.2.2) and it works as it did before.

**Comment by micahflee** [comment]
Yeah, it looks like the `get_hidden_service_conf` method is "New in version 1.3.0.": https://stem.torproject.org/api/control.html#stem.control.Controller.get_hidden_service_conf

And the jessie python-stem package is 1.2.2. Oops.

**Comment by micahflee** [comment]
I've confirmed that this works for me, but if you want to uninstall stem from pip, and just use the version in jessie, and confirm that this works on your end too, that would be cool.

**Comment by freddymartinez9** [comment]
``` 
$ pip show stem
---
Name: stem
Version: 1.2.2
```
I did a git pull after uninstalling and rebuild the deb using the latest version (0.8.1).  I am able to connect to the .onion and download the file using the new commits. 

thanks Micah!

**Comment by micahflee** [comment]
:+1:

**Comment by u451f** [comment]
There is a python-stem backport of the correct version: https://tracker.debian.org/pkg/python-stem 

I'll update the onionshare package dependencies to require this version of python-stem when using the onionshare Debian package.
