### ISSUE TITLE
No automatic compression for single files

### ISSUE THREAD

**Issue by omyno** [micahflee/onionshare#236]
When sharing a single file, in many cases it would be preferable to not compress the file into a .zip. Therefore, automatic compression could be disabled for single files by default.

**Comment by micahflee** [comment]
It's true that in many circumstances it's nicer to not compress single file shares, but some file types aren't already compressed, and zipping it could make the transfer go much faster. E.g. I imagine that large office docs don't have compression built-in.

A good example is if you create a 1GB file full of null bytes: `dd if=/dev/zero of=zeroes.dat bs=1M count=1024`, and then try sharing zeroes.dat over onionshare. If you zip it, the zip file is tiny, since a file full of the same bytes compresses really well, so it will transfer really fast. If you don't zip it, it's 1GB, and it will take hours to transfer.

On the other hand, http supports gzip compression. I wonder if flask is doing that with onionshare. It would be worth doing some tests. If we make sure that Tor Browser and the flask http server always do gzip, then probably the zip file is unnecessary for sharing a single file.

**Comment by blobgo** [comment]
Possibly just make it optional so that the user can select (in the settings) whether a single file should be compressed. You can expand it further by allowing the user to select how large the file should be at maximum to be send uncompressed.
So if you e.g. set 100 mb here the 1 GB file of zeros would be compressed, but all smaller files would just be send like they are.

**Comment by jvoisin** [comment]
Since there is a [dedicated package]( https://github.com/libwilliam/flask-compress ) to enable compression on Flask, I don't think that it can be done out of the box.

**Comment by micahflee** [comment]
I think you're right @jvoisin, it's not built-in to flask. And it looks like flask-compress isn't packaged by debian. So until that's the case, I'll mark this as wontfix.

**Comment by klawdhfzasjhaa** [comment]
Please make compression optional
