### ISSUE TITLE
Consider rate-limiting, to make URL shorter

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#238]
Right now a typical OnionShare URL looks something like this:

```
http://qtbq2bcfthyifgne.onion/tg24kk2htbrqlvirku2rjvuuou
http://( .onion domain )/( 16-byte random slug )
```

OnionShare assumes that .onion domains might not be private because there have been enumeration attacks against Tor to find otherwise unknown hidden services in the past.

That's why there's a slug: in case someone discovers the .onion domain, they also need to (basically) brute force a keyspace of 2^128 (16 bytes == 128 bits) in order to load the download page. The attacker will need to make at least 1 request, at most 2^128 requests, and on average 2^64 requests. OnionShare also uses constant time string comparisons, to prevent leaking any information about the actual slug, and making timing attacks not work.

To put this in perspective, 2^64 is 18,446,744,073,709,551,616. If each request takes .5 seconds (which is probably kind of fast for Tor hidden services, on average it would take 292 billion years. I think this is overkill, and slugs like `tg24kk2htbrqlvirku2rjvuuou` are really hard to type or tell people over the phone.

What if we introduced rate limiting? Say, OnionShare will only accept at most 20 404 requests before it automatically stops the server, giving the attacker a maximum of 20 guesses. This will already thwart timing attacks, because 20 requests isn't enough to successfully guess the first character of the slug.

What if the slug itself is a single word from the [securedrop wordlist](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/wordlist) (which is a modified diceware wordlist, with 6800 words). This means that the attacker has a 20/6800 chance of guessing correcting, or 0.2941%. What if the slug is two words? In this case the attacker has a 20/(6800^2), or 20/46240000, or 0.000043% chance. I think that's an unlikely enough chance.

This would mean instead of URLs looking like this:

`http://qtbq2bcfthyifgne.onion/tg24kk2htbrqlvirku2rjvuuou`

They could look like this:

```
http://qtbq2bcfthyifgne.onion/task-janus
http://qtbq2bcfthyifgne.onion/swami-buoy
http://qtbq2bcfthyifgne.onion/gyro-curt
http://qtbq2bcfthyifgne.onion/deter-trig
```

**Comment by garrettr** [comment]
> The attacker will need to make at least 1 request, at most 2^128 requests, and on average 2^64 requests.

The attacker will have to make 2^127 requests on average, because half of 2^128 is 2^127.

**Comment by garrettr** [comment]
All of your estimates for the timing of attacks implicitly assume that your adversary is only capable of making one request at a time and/or the service under attack (Tor/OnionShare) is only capable of responding to one request at a time. This is probably a bad assumption, and underestimates your adversary's advantage.

**Comment by garrettr** [comment]
> What if we introduced rate limiting? 

This is not a bad idea, but it should be considered carefully. The main risk in introducing rate limiting is it can create a DoS vector. For example, if an attacker can enumerate hidden services and identify a new OnionShare THS before it has been connected to by the intended user, they can just fire off N invalid requests and cause the rate limiting to terminate the connection.

In the context of OnionShare, I don't think this is much of a concern because there is an expectation that both parties are online simultaneously to do the file transfer, and so the latency between creating the new hidden services and the valid user connecting to it is probably on the order of minutes (not hours or days). I'm not sure how quickly all hidden services can be enumerated, but it probably takes significantly longer than the median latency for connecting to an OnionShare.

**Comment by micahflee** [comment]
> The attacker will have to make 2^127 requests on average, because half of 2^128 is 2^127.

Touche.

And also good point about the estimates being low. But I think in any case it's in the same order of magnitude. There's an upper limit to how many concurrent connections the Tor network itself can support. I think for most situations OnionShare just needs to be able to survive attacks for a period of hours, and occasionally days. There may be edge cases where an OnionShare needs to be up for longer than that, but by their very nature they're ephemeral and short-lived.

This would introduce a sort of DOS attack, but one that can be handled very gracefully -- the sender can receive a message in their UI explaining that the server stopped to prevent a potential attack. It fails closed.

While .onion enumeration attacks are assumed possible and part of the threat model, in practice they normally take longer than the life of an OnionShare HS to pull off (if I remember correctly, the attack normally takes weeks?). So in practice, I think it will be very rare that any attacker will be in the position to perform this DOS attack, and if they are they'll only be in the position to be annoying -- they won't be able to guess the URL and download the file.

So I think the trade-off is probably worth it, for more readable and typable URLs.

**Comment by garrettr** [comment]
> This would introduce a sort of DOS attack, but one that can be handled very gracefully -- the sender can receive a message in their UI explaining that the server stopped to prevent a potential attack. It fails closed.

It would be nice to display such a helpful error message to the user, but the concern is that the attacker would be able to prevent the connection from ever succeeding. Therefore, after such an event, we should rotate the hidden service address to force the attacker to re-enumerate all hidden services before being able to attack again.

> While .onion enumeration attacks are assumed possible and part of the threat model, in practice they normally take longer than the life of an OnionShare HS to pull off (if I remember correctly, the attack normally takes weeks?)

The most recent [paper](http://www.ieee-security.org/TC/SP2013/papers/4977a080.pdf) (Section 5.b) that I know on this topic presents an attack that can enumerate all Tor Hidden Services in 2 days using modest resources. However, that was based on the default requiring a relay to have an uptime of just 24 hours to receive the HSDir flag. That has since been increased to [96 hours](https://trac.torproject.org/projects/tor/ticket/14149), so I believe this attack will now take at least 5 days (4 days to get the HSDir flag on their malicious relays, and 1 day for all the HS's to rotate their descriptors).

This attack requires adding ~50 Tor relays to the network, so it's possible that it could be detected and blocked by the directory authorities before it has a chance to finish the enumeration (although you should not rely on that assumption for security, it has [failed in the past](http://fusion.net/story/238742/tor-carnegie-mellon-attack/)).

**Comment by garrettr** [comment]
It's important to note that when I described the hidden service enumeration attack in my last comment, I said it would take 5 days, but most of that time is taken up by getting malicious relays into the Tor network and waiting for them to get the HSDir flag. Once they've gotten that flag, I think it would only take them a maximum of 24 hours for them to detect new hidden services as they are added to the network.

**Comment by blobgo** [comment]
I think rate limiting is a good idea, but please make it optional so that - in case it fails or I do not mind about a long address (because I do not tell it over phone) - I can use the "old" long URLs.

**Comment by jvoisin** [comment]
I fail to see how rate-limiting could be a good idea:
- it doesn't add anything security-wise (since the attacker can't guess the domain, and it would take something like 133 days to guess the slug at a 2 request per second guess).
- it adds complexity.
- it's a potential DoS vector (please don't introduce captcha to fix this).

Why do you want to implement this?

**Comment by micahflee** [comment]
@jvoisin I regularly use onionshare to send files to myself between computers, or between VMs that don't support shared filesystems or clipboards. Because of this I end up having to look at an onionshare URL in one window and then type it in another window or on another computer. And it's less common, but I've communicated onionshare URLs by reading them out loud, or by copying the URL into my phone to text to someone. It's way easier to type `gyro-curt` than `tg24kk2htbrqlvirku2rjvuuou`.

It doesn't make onionshare more secure, and it does add complexity, but it makes onionshare more usable for all use-cases that don't involve copying and pasting the URL.

The DoS vector is only exploitable if an attacker has already enumerated the .onion and is actually trying to guess the slug -- if this happened it would be safest to stop the HS and start a new one anyway. It's very unlikely that someone will fail to copy/paste or type the slug 20 times in a row by mistake, especially with the slug being human readable now.

I still could be convinced that this feature is a bad idea. But since I think it makes onionshare more usable while preserving the same level of security, it sounds like a win.

**Comment by jvoisin** [comment]
The rate-limit won't add anything then, if the attacker can't enumerate .onion.
If you're sharing a document to more than 20 people, you'll need to restart Onionshare. If I'm among the group, I could deny access to other people, forcing you to start a new Onionshare instance for each person if you want to be sure that everyone gets the document.

It could decrease the usability, while adding nothing in terms of security. I don't think that this feature is really super-harmful, but I do think that it's useless :)

**Comment by micahflee** [comment]
Ah I think I see the confusion. The counter should only get incremented on 404 requests, but not any any requests that include the valid slug (the index page and the actual download request). So if you're sharing a document with more than 20 people, the service will only close if you share the wrong URL and everyone who loads it gets 404 errors. If you share the right URL, no one will notice a difference, except that the URL is shorter.

And if one of those people isn't copying and pasting into Tor Browser but rather trying to manually type the URL, it'll only close if that person fails to type something like "deter-trig" 20 times in a row.

**Comment by micahflee** [comment]
Of course, a malicious recipient of a group OnionShare could DoS the rest of the recipients. If you like, tweet an OnionShare URL, anyone who sees the tweet could spoil the fun. That's kind of an edge-case threat though. I haven't been considering one recipient in a multi-recipient share as part of the threat model.

**Comment by jvoisin** [comment]
I still stand by my last-paragraph ;)
