### ISSUE TITLE
Let us download multiple files

### ISSUE THREAD

**Issue by blobgo** [micahflee/onionshare#252]
Instead of "close server automatically" I would like a more specific option like "Close server after X downloads" where X is the number of downloads you want to alllow.

By default X may be set to 1 - this would be like the current behaviour.

**Comment by garrettr** [comment]
See #248 for related issues around multiple downloads and the UI.

**Comment by micahflee** [comment]
I can see this being useful if you're like "I want Alice, Bob, and Charlie to download this file." But because all clients connect to the server anonymously, there's really no way to tell which users are downloading your files, so I don't think this really makes sense. Maybe Alice downloaded the file twice, and then Bob downloaded it, and then the server closes before Charlie gets a chance to download.

If you really want to make sure that Alice, Bob, and Charlie all get it, you should run OnionShare three times and give them each a separate URL to download.

But yeah I agree, let's use #248 for discussing multiple download features.
