### ISSUE TITLE
Weird /tmp usage in hs.py

### ISSUE THREAD

**Issue by jvoisin** [micahflee/onionshare#258]
In the `hs.py` file, there is this:
```
                path = '/tmp/onionshare'
                try:
                    if not os.path.exists(path):
                        os.makedirs(path, 0700)
                except:
                    raise HSDirError(strings._("error_hs_dir_cannot_create").format(path))
                if not os.access(path, os.W_OK):
                    raise HSDirError(strings._("error_hs_dir_not_writable").format(path))

                self.hidserv_dir = tempfile.mkdtemp(dir=path)
```

Why specifying `/tmp/onionshare` instead of letting `mkdtemp` decide?

**Comment by micahflee** [comment]
Good question. I feel like it may have had something to do with AppArmor knowing where Tor is trying to write the hidden service files? But since ephemeral hidden services are now in stable Tor, this code path should only get executed with old versions of Tor.

I wonder at what point I should drop support for earlier versions of Tor.

**Comment by jvoisin** [comment]
Support only the version packaged in the latest Tails - 1 ?

**Comment by u451f** [comment]
Looks like there is now a pull request to fix this: https://github.com/micahflee/onionshare/pull/288...... and a CVE.
