### ISSUE TITLE
Digital signature for OnionShare_Setup.exe is invalid

### ISSUE THREAD

**Issue by schlimazel** [micahflee/onionshare#276]
I'm finding that the installer file for OnionShare 0.9 returns an invalid digital signature. 

(I had the same problem with the previous release, 0.8.1.)

However, the file's PGP signature is valid.

I have no trouble validating the digital signatures for other files, just OnionShare_Setup.exe.

I'm using Vista but it's kept up-to-date with the latest patches and software versions.

Thank you.

**Comment by micahflee** [comment]
This is referring to the Windows Authenticode signature, not the PGP signature.

In Windows 10 the signature checks out as valid for me.

When I tested this release in Windows 7 I used one of Microsoft's free [Internet Explorer testing VMs](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/mac/) and the signature didn't validate in those VMs.

So I uploaded the OnionShare_Setup.exe to [VirusTotal](https://www.virustotal.com/en/file/b5d57d946a2cc60d64dd8a927beabb65dfb2d066b7ad5fe078158efad974e580/analysis/), and it confirmed: "Signed file, verified signature" (it also has a handful of false positives from AV software...)

I figured that probably there was an issue with the Windows 7 VM and it didn't contain a complete trust chain or something. But since this is happening to @schlimazel in Windows Vista, now I suspect that the signature is only verifying in newer version of Windows.
