### ISSUE TITLE
Please kill legacy functions

### ISSUE THREAD

**Issue by jvoisin** [micahflee/onionshare#278]
It would be great if onionshare could get rid of its legacy code, since it's not super-tested nor maintained, and some stuff are not even working.

In the `hs.py` file, the function `wait_for_hs` isn't even working in Python3 (`urllib.request.urlopen('http://{0:s}'.format(onion_host))` won't work, since there is no `request` thingy in the `urllib` module).

**Comment by micahflee** [comment]
`wait_for_hs` does work in python3, and in fact isn't actually a legacy function yet (despite the comment saying that it is, which is horrible). The python3 GUI always calls it, even if ephemeral hidden services are available, because it can be called in a separate thread without blocking the GUI thread (causing the window to appear to stop responding in ubuntu, OSX, etc).

Note this line in the HS start method: `res = self.c.create_ephemeral_hidden_service({ 80: port }, await_publication = False)` -- if `await_publication` were true then `wait_for_hs` would no longer be necessary, but the window would freeze until the hidden service was ready.

The `urllib.request.urlopen('http://{0:s}'.format(onion_host))` actually just doesn't get called unless `transparent_torification` mode is on, which isn't fully supported yet (intended for Tails and Whonix).

But I agree, I want to remove legacy functions, and I also want to remove all non-ephemeral hidden service support altogether (#289, #292). But it occurs to me that debian jessie will, probably forever, rely on this legacy code, because it ships with too old versions of stem and tor. I wonder how much I should care... my current thinking is that version 1.0 will remove legacy support, and simply won't be compatible with jessie (without apt pinning from something newer, of course).

**Comment by micahflee** [comment]
This is related to #292. As soon as Debian Stretch is stable (the code freeze is Feb 5, 2017), I'm going to make a release that removes support for non-ephemeral hidden services. Stretch will come with a version of python3-stem greater than 1.4.

**Comment by intrigeri** [comment]
Even jessie-backports now has Tor 0.2.9, so IMO there's no real need to wait for the Stretch freeze.
