### ISSUE TITLE
question: is there a way to start onionshare with a consistent sharing url?

### ISSUE THREAD

**Issue by ghostlands** [micahflee/onionshare#295]
I had trouble finding a mailing list for OnionShare, so I apologize for cluttering the tracker.

The appropriate language is difficult to parse for this request; hopefully I won't use incorrect terminology. Persistent address? Static address? I'm looking for a solution to serve files using the same .onion address, but not necessarily consistently, in other words I intend that the link won't always be available. Users wanting to download from the link may or may not find it, depending on whether I'm running the server.

The use case involves intermittent connectivity, including the need to shut down the server for physical security, while still having a link address that can be consistent in order to be able to publish somewhere consistent. Potential user/downloaders needing to employ trial and error over time is acceptable; it could also be used as part of a larger mechanism where an automated system queries a known address at predetermined intervals and downloads the information at the link whenever it goes live.

Obviously ephemeral addresses should be the default, but it would be really helpful to have this as an option.

**Comment by choltz95** [comment]
I don't think onionshare supports passing a private key as an argument or reading from a persistent hidden service directory for ephemeral or standard hs.

I like the idea though.

**Comment by ghostlands** [comment]
It ultimately wouldn't even have to automatically read a persistent directory. The drag and drop interface is easy and simple enough that the files could be manually added each time. The content desired for that address might change anyway. The primary device required would be the consistent key.

**Comment by micahflee** [comment]
@ghostlands sorry about not responding for so long. OnionShare doesn't have a mailing list, but perhaps I should make one. And @choltz95 is correct. In order to start an onion service with the same URL, you need to supply tor with the same private key.

At the moment, OnionShare creates an ephemeral onion service, but there's no feature to export the private key. And there's also no feature to start an share by providing a private key. I do think it would be a decent feature to support, but only if it can be done in such a way that doesn't have a really confusing UI.

**Comment by micahflee** [comment]
This is a pretty good idea for UI. I'd want to spec it out slightly more, but I think it can work. The next version of OnionShare will already have advanced options, too, to create stealth onion services.

**Comment by BenjaminHCCarr** [comment]
@ghostlands I think this is a great idea. If you haven't heard of it, you may want into @HelloZeroNet, they use the onion network with distributed file sharing, etc, so even if you're not online a copy might be:

https://github.com/HelloZeroNet/ZeroNet

**Comment by micahflee** [comment]
Note that now in order to make this feature, we need to keep track of whether or not the onion service is stealth, and if it is also export the HidServAuth stuff.

**Comment by gerontimo** [comment]
I do share ghostlands wish for the new feature.
Presently onionshare needs synchronous communication via some other channel to transmit the URL and possibly the "HidServAuth". 
This means you cannot hide your communication/relationship with your partner against the adversary. If onionshare would allow to predetermine the URL, you could fully hide the fact that the two of you are communicating at all. 
You would do this by exchanging encrypted files containing an appointment for the next exchange. This appointment must neccesarily contain the future onionshare URL in addition to the time. Such communication would just need to be primed once via an out of band channel.
Presently the need for synchronous communication to prime each single onionshare transfer imho limits the strength of onionshare. If you e.g. use two TORed, anonymous e-mail accounts, the attack surface for deanonymization is large. Appointment Enabled Onionshare would short circuit this cumbrous procedure.
If there would be some conflict between offering Stealth Onion Service and the Appointment Enabling, I would gladly let go the cumbersome Stealth Service since transfer files can easily be secured by encryping independently with a "negligible adversary advantage" cipher (I am doing this anyways).
I presently know no other tool allowing to hide the communication relationship with your partner altogether. Appointment Enabled Onionshare would be the first.

**Comment by ghostlands** [comment]
Thanks for making this happen <3 ^_^
