### ISSUE TITLE
Filenames aren't escaped

### ISSUE THREAD

**Issue by jvoisin** [micahflee/onionshare#319]
What if I share a file named `<img src="x" onerror="alert(1)">`?

![xss]( https://i.imgur.com/UIfAhd1.png )

**Comment by commandnotfound** [comment]
I can confirm that a file named `<img src"x" onerror="alert(1)"> does this, both in Tor Browser and in Chrome (when invoking `onionshare` using the `--local-only` flag). Upon closer inspection, after dismissing the alert box, one can see a broken image link (since the filename is `x`, which leads to nowhere) in lieu of a file name.

This would indicate that there is no sanitation of html tags in filenames.

**Steps to Reproduce**
1. Use the latest version of `onionshare`
2. Share a file with an HTML tag in it. For example, `<img src="x" onerror="alert(1)">`.
3. Visit the URL provided in your browser.
4. In the case of the example, notice a dialog box. After dismissing dialog box, notice the broken image where a filename should be.

Perhaps, when compiling the names of files and directories, we could sanitize these names of any HTML tags.

**Comment by micahflee** [comment]
Thanks for reporting this @jvoisin, and sorry for neglecting it for so long. Interesting, in newer versions of python3-flask (like the one that comes with Debian stretch), I can't reproduce. It just escapes the HTML. But when I try it with python3-flask from Debian jessie, I can reproduce.

**Comment by jvoisin** [comment]
@micahflee The mitigation that you merged is bypassable. Please read my previous comment.
A harmless example would be a file named `<form`, resulting in a [dangling markup attack]( http://lcamtuf.coredump.cx/postxss/ ).

**Comment by garrettr** [comment]
> Thanks for reporting this @jvoisin, and sorry for neglecting it for so long. Interesting, in newer versions of python3-flask (like the one that comes with Debian stretch), I can't reproduce. It just escapes the HTML. But when I try it with python3-flask from Debian jessie, I can reproduce.

@micahflee I dug into this a bit with @commandnotfound the other week, here's what we found.

When I first saw this issue I was shocked, because I knew from my previous contributions to OnionShare that you were using Flask and generating the HTML with templates. Flask _should_ be auto-escaping template variables by default.

According to Flask [documentation](http://flask.pocoo.org/docs/0.12/templating), it does:

> Unless customized, Jinja2 is configured by Flask as follows:
> * autoescaping is enabled for all templates ending in .html, .htm, .xml as well as .xhtml when using render_template().
> * autoescaping is enabled for all strings when using render_template_string().

*However*, while this behavior has long been the default for templates rendered via `render_template`, it was only [recently](https://github.com/pallets/flask/pull/1176) also made the default for templates rendered via `render_template_string`. Specifically, this change [landed](https://github.com/pallets/flask/commit/db09c6798eb4304aa3e6e937517bf94acd449c8f) in **Flask 0.11**.

@micahflee, you said:

> Interesting, in newer versions of python3-flask (like the one that comes with Debian stretch), I can't reproduce. It just escapes the HTML. But when I try it with python3-flask from Debian jessie, I can reproduce.

Debian's `python3-flask` package uses Flask **0.10.1** in [stable/Jessie](https://packages.debian.org/jessie/python3-flask), but the version in [stretch](https://packages.debian.org/stretch/python3-flask) is upgraded to **0.11.1**.

**Comment by garrettr** [comment]
@micahflee I don't think https://github.com/micahflee/onionshare/commit/cff11cd7e48fe4e94ef484ba1f1095362330452d is a good fix for this issue either.

Using `html.escape` in `set_file_info` fails to properly separate concerns.

There are a multiple ways in which the user-provided filenames could be dangerous. In this issue, the problem is that filenames may contain characters that have a different meaning in a different context, such as an HTML template. Another potential issue is that filenames are maliciously chosen to overwrite other files when the unpacked as part of an archive: for example, see the warnings in the Python documentation for [`ZipFile.extractall`](https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.extractall) or [`TarFile.extractall`](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.extractall).

Using `html.escape` at the top of `set_file_info` confuses these (different) issues: now HTML-escaped filenames are used everywhere, not just when rendered in HTML. The meaning of characters from filenames in HTML is only a safety concern in the context of interpolating them into an HTML template, so auto-escaping should be handled at the boundary between the potentially unsafe data and the template renderer (indeed, this is where Flask does it in `render_template`, and where most safety-conscious template engines do it).

Finally, https://github.com/micahflee/onionshare/commit/cff11cd7e48fe4e94ef484ba1f1095362330452d fails to do anything to prevent this type of issue from happening in the future. If future code changes pass other potentially unsafe/user-controlled variables to `render_template_string`, content injection is still possible in the general case.
