### ISSUE TITLE
Download page sometimes not working

### ISSUE THREAD

**Issue by github-user-1** [micahflee/onionshare#341]
Sometimes I get the following page for download right away when opening the download link (see screenshot below) so I can't download the file(s) actually. Most of the time it's working fine, but sometimes not - unfortunately, I can't reproduce it. Everything else is looking perfectly fine (e.g. the onionshare-app itself, tor browser is working and connected,...).

![zwischenablage01](https://cloud.githubusercontent.com/assets/6796538/21749287/cba71abc-d593-11e6-9686-2cae0b67874f.gif)

**Comment by micahflee** [comment]
The "Stop sharing automatically" option restricts the specific share to one download. That "OnionShare download in progress" page happens when you load the download page, but someone is already downloading the file. Basically, you should only see that if you (or someone else) is currently downloading the file.

**Comment by micahflee** [comment]
When you load the the download page `/[slug]` or the download itself `/[slug]/download`, it checks to see if `download_in_progress` is true. If it is, it displays this page instead of the normal download page: https://github.com/micahflee/onionshare/blob/master/onionshare/web.py#L185 https://github.com/micahflee/onionshare/blob/master/onionshare/web.py#L213

The only part of code that sets `download_in_progress` to true is after you start a download: https://github.com/micahflee/onionshare/blob/master/onionshare/web.py#L245

So I'm pretty sure that you must have started a download, and then refreshed page, to see this. (Or maybe someone spied on the onionshare URL and started downloading it before you go to it.) It's possible I'm wrong, but for now I'm going to close this until you can figure out a way to reproduce it.
