### ISSUE TITLE
Use ADD_ONION Flags=DiscardPK?

### ISSUE THREAD

**Issue by adrelanos** [micahflee/onionshare#342]
Why? I really don't have a good reasoning yet. Cannot hurt, no? Perhaps improves better anti forensics? And as a general rule of thumb to prevent gathering and processing data that is not required, seems sensible to me.

**Comment by micahflee** [comment]
Normally I'd agree, but I think actually I might not use this flag because in the future I'm hoping to implement #295. This implementation would have to keep track of the key for every onion service, just in case the user would like to export it. And at the moment it doesn't seem to hurt -- it just means the key might temporarily be in memory in the python process and the tor process, rather than just the tor process.
