### ISSUE TITLE
Connected to 127.0.0.1:9050, but can't authenticate. Maybe this isn't a Tor controller?

### ISSUE THREAD

**Issue by 2SI3NX** [micahflee/onionshare#374]
Why cant this authenticate?  There is no password. tor service is used for other apps as well and its working correctly but this isnt.

**Comment by 2SI3NX** [comment]
By the way, this is only when i click on "Test Settings"

**Comment by micahflee** [comment]
OnionShare needs to connect to the Tor control port, which is different than the SOCKS proxy port. Port 9050 is a SOCKS proxy, which basically allows programs to make network connections over Tor, but OnionShare needs to actually be able to control the Tor service itself, so it can tell Tor to start new onion services. By default this is on port 9051.

However just trying port 9051 probably won't work either, because by default connections are restricted. Check out the wiki here for instructions on how to do this for Windows, Mac, and Linux: https://github.com/micahflee/onionshare/wiki/Connecting-to-Tor#using-a-system-tor

**Comment by micahflee** [comment]
Note that if you're using Linux or a Mac, I recommend connecting to the Tor controller using a socket file instead of the control port.

**Comment by 2SI3NX** [comment]
Ok thanks, and Yes now i used: sudo usermod -a -G debian-tor username and its working now.   I know this is the easiest option, but Is this option safe though? I mean, by adding the user to the debian-tor group, would this be risky for the system in any possible way?

**Comment by micahflee** [comment]
Yes it's safe. It's actually a bit safer than using the control port with a password. Basically, it's saying that your user is allowed to control the Tor daemon running on your computer. With the control port, it's saying that anyone who can connect to that port and has the right password is allowed to control the Tor daemon. So theoretically, some other user on your system might be able to connect to the control port and guess the password that way. But this way the access control is guaranteed by linux file permissions.
