### ISSUE TITLE
E: Unable to locate package onionshare

### ISSUE THREAD

**Issue by subscriptionblocker** [micahflee/onionshare#383]
(shrug) Followed all instructions. Played a bit with capitalization - then gave up.

**Comment by jamieduk** [comment]
Same i get error and i inserted ppa and updated no issue please help?

**Comment by subscriptionblocker** [comment]
This is Ubuntu 14.04 (Zorin) . I cannot understand why I still get the error "Unable to locate package onionshare".

**Comment by mig5** [comment]
@micahflee it does indeed look like Onionshare is missing from your PPA for Trusty (14.04). Presumably because newer Stem is required?

I only see onionshare packaged for Artful, Zesty, Yakkety and Xenial

Perhaps https://github.com/micahflee/onionshare/wiki/Linux-Distribution-Support should be updated to explain which distros ought to manually install from source?

**Comment by mig5** [comment]
Ubuntu users who don’t find the package in their distro version can install from source per the BUILD.md and https://github.com/micahflee/onionshare/wiki/Linux-Distribution-Support
