### ISSUE TITLE
In Settings, clicking on selected radio buttons unselects them

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#386]
For example, if "Use Tor that is bundled with OnionShare" is selected, and you click it again, it unselects it so that nothing is selected. It shouldn't unselect the option, it should keep it selected.

**Comment by mig5** [comment]
I'm a bit of a Python GUI noob, but I did some research, and apparently this is because the radio buttons were not within their own exclusive group widget.

When qradiobuttons are in their own widget, they get the 'autoExclusive' true, which forces one to be checked at all times e.g they can't be all untoggled.

See https://doc.qt.io/qt-4.8/qradiobutton.html

"Radio buttons are autoExclusive by default. If auto-exclusive is enabled, radio buttons that belong to the same parent widget behave as if they were part of the same exclusive button group."

https://github.com/micahflee/onionshare/pull/388
