### ISSUE TITLE
Why does the macOS pkg not have a sig?

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#443]
Why does the macOS pkg not have a PGP sig? Verifying the download based on the fingerprint of the certificate used to sign the pkg is not a easy solution.

**Comment by micahflee** [comment]
For a long time I've provided PGP signatures for the Windows and Mac binaries, but at the same time I also used the built-in operating system codesigning, which makes it somewhat redundant.

Because adding an extra signature is redundant, is pretty confusing for people who don't know what it is, a very small minority of users actually download it (for OnionShare 1.0, `OnionShare.pkg` was downloaded 2,787 times, and `OnionShare.pkg.sig` was downloaded 130 times), and it increases the work to do to make a release, I decided to just stop providing them.

Windows releases are codesigned using [Authenticode](https://msdn.microsoft.com/en-us/library/ms537359(v=vs.85).aspx), and macOS releases are codesigned using [Gatekeeper](https://support.apple.com/en-us/HT202491).

**Comment by Baccount** [comment]
Can you post the SHA-256 fingerprint of your Developer ID Certificate for the PKG installer on your website or GitHub, so that users have a way to verify that the download has not been tampered with.
![sha256](https://user-images.githubusercontent.com/10781882/27468332-198af352-579e-11e7-8d15-e5a681ce0a8b.png)
