### ISSUE TITLE
OnionShare's progress bar is inaccurate

### ISSUE THREAD

**Issue by sm000th** [micahflee/onionshare#446]
Here's an example, when I just clicked to download the progress bar went to 10%:

![](https://raw.githubusercontent.com/sm000th/screenshots/master/screen1.png)

When the download started it was way too off with the actual download speed and time:

![](https://raw.githubusercontent.com/sm000th/screenshots/master/screen2.png)

**Comment by Baccount** [comment]
The onionshare progress bar shows how much of the files have been send out to tor, it can not detect how much of the zip file has been received by the end user, and it is very hard to estimate how long it will take a file to complete a transfer, because of the bandwidth in tor is variable and the ping can be very high.

**Comment by micahflee** [comment]
I noticed this when I developed the very first version of OnionShare, and it's so cool :dizzy:.

Like @Baccount said, the progress bar in the OnionShare GUI only measures how much of the file has been uploaded. As soon as it gets to 100%, then 100% of the file has been uploaded. On the other end, the progress bar in Tor Browser shows how much of the file has been downloaded.

Tor onion services bounce your connection through 7 nodes around the world. So if OnionShare's progress bar is 100%, but Tor Browser's progress bar isn't quite there yet, this means that remaining part of the file has already left the sender's computer and is still bouncing around the internet before it finally makes it to the receiver's computer.
