### ISSUE TITLE
magic-wormhole sharing style (using mnemonic words and tab word completion)

### ISSUE THREAD

**Issue by adrelanos** [micahflee/onionshare#449]
https://packages.debian.org/de/stretch/magic-wormhole

https://github.com/warner/magic-wormhole

https://us.pycon.org/2016/schedule/presentation/1838/

Usability wise one of the most usable and useful tools I've found in a while. Easier than sharing a link to an onion, thanks to memonic words and tab word completion.

Do you think you could add this to onionshare?

**Comment by rahiel** [comment]
@adrelanos note that magic-wormhole is already usable through Tor (with the `--tor` flag) and they [want to add transfer through hidden services](https://github.com/warner/magic-wormhole/issues/8).

**Comment by micahflee** [comment]
magic-wormhole is a very cool project, but I don't see how it could really be incorporated into OnionShare as it currently exists because the client is Tor Browser itself, and there is no central OnionShare server that could be used to coordinate the share.

However, adding a feature to magic-wormhole to start using onions sounds like a great idea.
