### ISSUE TITLE
Onionshare icon double bounce

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#451]
When I open onion share the icon will bounce 2 times very fast. Onion share is the only app that has this issue. I attached a video showing the issue.
[bug.mov.zip](https://github.com/micahflee/onionshare/files/1073689/bug.mov.zip)

**Comment by mig5** [comment]
I looked into this, and I’m pretty sure it’s just because the program uses PyInstaller, which means launching the app actually executes a bootloader which in turn launches the real app underneath (correct me if I’m wrong @micahflee)

So what you see in OS X as a quick ‘double bounce’ is the succession of two executions.

I could not find a way to change this, other than setting LSBackgroundOnly to True, which prevents the dock icon bounce entirely.

**Comment by micahflee** [comment]
@Baccount did #540 resolve this for you?

**Comment by Baccount** [comment]
Yes the bug is fixed.
