### ISSUE TITLE
Post the SHA-256 fingerprint of your Developer ID Certificate for the PKG installer

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#452]
Can you post the SHA-256 fingerprint of your Developer ID Certificate for the PKG installer on your website or GitHub, so that users have a way to verify that the download has not been tampered with.
![sha256](https://user-images.githubusercontent.com/10781882/27468368-47b00682-579e-11e7-8538-7de71daf100f.png)

**Comment by micahflee** [comment]
There's a terrible macOS packaging bug with python, Qt, and both PyInstaller and py2app where, if I build packages on newer Mac hardware, it crashes with `Illegal instruction: 4` when running on older harder (~2013 or older). See #274. There was also a packaging issue where if I build packages on newer versions of macOS, it fails to run on older versions of macOS.

So, since I want to support macOS 10.9+, and also older Mac hardware, I have a dedicated build machine that's an old Mac running macOS 10.9.5. This computer has the only copy of my Developer ID Certificate, but unfortunately this old version of macOS doesn't show my sha256 fingerprint, only sha1 and md5.

![screen shot 2017-09-13 at 5 12 10 pm](https://user-images.githubusercontent.com/156128/30406581-88e35498-98a7-11e7-9b43-7c0f79a07443.png)

My sha1 fingerprint matches what's in your screenshot. Any idea what command I might run to learn the sha256 fingerprint?

**Comment by Baccount** [comment]
sorry for the long delay, I found that I can run the command 
codesign -dv --verbose=4 /Applications/Fantastical\ 2.app 
and the result I get is
![issue](https://user-images.githubusercontent.com/10781882/31929911-8b156d6c-b852-11e7-8dcd-ea093acf8a55.png)

**Comment by Baccount** [comment]
After the pkg is signed you can open it and click the lock icon in the upper right, and click the expand button next to details, scroll to the bottom and you will see the sha-256 fingerprint.
CB 58 EB F9 F3 A5 A7 FF 87 55 E9 99 CA 72 6B C9 01 6F BD 0C DA 0D 05 F2 93 0A 76 F4 32 3F CF 52

**Comment by micahflee** [comment]
Unfortunately, that doesn't appear to work in macOS 10.9.

```
dumbledore:~ m$ codesign --display --verbose=4 /Applications/OnionShare.app
Executable=/Applications/OnionShare.app/Contents/MacOS/onionshare-gui
Identifier=com.micahflee.onionshare
Format=bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=13928 flags=0x0(none) hashes=689+3 location=embedded
Hash type=sha1 size=20
CDHash=d7cb905b79813471c9edf96b75e7a9ad372244e5
Signature size=8516
Authority=Developer ID Application: Micah Lee (N9B95FDWH4)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=May 30, 2017, 3:57:05 PM
Info.plist entries=10
TeamIdentifier=N9B95FDWH4
Sealed Resources version=2 rules=12 files=119
Internal requirements count=1 size=184
```

I think for now you can just rely on the SHA1, plus the fact that my certificate is signed by Apple's certificate. At some point in the future, when OnionShare drops support for 10.9, I'll post the full SHA256 checksum.

**Comment by micahflee** [comment]
I've upgraded my build machine to macOS 10.11.6, but unfortunately it still doesn't include sha256 fingerprints:

![screen shot 2018-01-18 at 4 16 39 pm](https://user-images.githubusercontent.com/156128/35128539-02d3b98c-fc6c-11e7-8e37-5ee00fdd5bbb.png)

It looks like the codesign command shows a sha256 for the actual OnionShare 1.2 .app though:

```
$ codesign --display --verbose=4 /Applications/OnionShare.app
Executable=/Applications/OnionShare.app/Contents/MacOS/onionshare-gui
Identifier=com.micahflee.onionshare
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=21912 flags=0x0(none) hashes=679+3 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha1=a2d48ee3b0e24928045788b760732429acb3cebd
CandidateCDHash sha256=0cd0fec0e0e4d22ab0f8dce0ee2867155d0fe634
Hash choices=sha1,sha256
CDHash=0cd0fec0e0e4d22ab0f8dce0ee2867155d0fe634
Signature size=8907
Authority=Developer ID Application: Micah Lee (N9B95FDWH4)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Jan 18, 2018, 3:00:11 PM
Info.plist entries=10
TeamIdentifier=N9B95FDWH4
Sealed Resources version=2 rules=12 files=127
Internal requirements count=1 size=184
```
