### ISSUE TITLE
If Onionshare is set to use TorBrowser to connect and you make start a share and when the share is active in onionshare then you close TorBrowser

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#500]
If Onionshare is set to use TorBrowser to connect and you make start a share and when the share is active in onionshare then you close TorBrowser, there is no error message in Onionshare even though the onion-servive service is offline.
Steps.
1. Open onionshare and make sure that it is set to connect to TorBrowser.
2. Open Torbrowser and then start a file share in onionshare.
3. While the share is active Close TorBrowser.
4. The onion service will go down but onionshare still shows that the share is still active.

Related to #493

**Comment by mig5** [comment]
I have added a fix for this into the PR at #494 since it's indeed very closely related, maybe you want to test it out @Baccount?

In theory this works for other types of 'Tor got disconnected' e.g not just Tor Browser method but bundled or sockets. It also partially solves #370 e.g if the internet connection is lost, the server will alert and stop. (Fun side fact: if combined with the private-key-saving feature in #485, you would in theory be able to start the server back up again later under the same URL when you fix your Tor/Internet connection)

**Comment by Baccount** [comment]
A error message is correctly displayed when when closing TorBrowser, Thank you mig5 for the fast and Excellent patch.

**Comment by mig5** [comment]
Hmm I think I have found more corner cases with the 'bundled' Tor, I might have to close the PR and work on it some more :( sorry

**Comment by mig5** [comment]
A better PR hopefully https://github.com/micahflee/onionshare/pull/503

**Comment by micahflee** [comment]
Looks like #503 fixes both this and #493.
