### ISSUE TITLE
When a user chooses to use the Tor bundled with onionshare, should onionshare check for a newer version of Tor available?

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#505]
When a user chooses to use the Tor bundled with onionshare, should onionshare check for a newer version of Tor available and warn uses that the bundled version is outdated and recommend them to use the TorBrowser configuration option instead? Because Onionshare's bundled Tor version sometimes contains vulnerabilities that have been patched newer versions. Onionshare 1.1 contains a version of Tor that is vulnerabilities  to TROVE-2017-009 TROVE-2017-013 other [vulnerabilities](https://blog.torproject.org/new-stable-tor-releases-security-fixes-0319-03013-02914-02817-02516) both of those vulnerabilities directly effect V2 onion services. 

**[TROVE-2017-009](https://trac.torproject.org/projects/tor/ticket/24244): Replay-cache ineffective for v2 onion services** _SEVERITY: Medium_
**[TROVE-2017-013](https://trac.torproject.org/projects/tor/ticket/24430): Use-after-free in onion service v2** _SEVERITY: High_

**Comment by mig5** [comment]
It would be tricky because there is no guarantee that a newer version of Tor is actually bundled with the latest version of Tor Browser yet (for example, it took 8 days before Tor Browser 7.0.11 was released with the security-fixes-included Tor 0.3.1.9). 

So telling a user to switch to Tor Browser might not mean they're any more secure than bundled, so would create a false sense of security.

There's not even a sane way of telling if there's a new 'official' Tor release beyond some sort of parsing of https://archive.torproject.org/tor-package-archive/. They don't use any sort of 'latest' symlink technique that could be relied on.

Then there's Linux users, where the 'bundled' Tor is not really bundled but system-provided, so even there, they may need to install updates to obtain fixes, but those updates might not land in all the Linux distributions at the same time. This could be complicated to check since (at least on Debian based systems) you require administrative privileges to do an apt check to see if there's updates avialable. On Whonix I think they even package their own Tor on their own schedule.

I don't think it's a bad idea but just that it would be impossible to reliably implement.


The 'bundled Tor' feature is awesome, but you could say it's placed a burden that didn't previously exist to 'keep up' with Tor's release cycle. 

It might be nice to someday get a 'team' of developers to help reduce the pressure and relieve Micah from being a single-point-of-failure. Maybe if the project was part of Tor Project's suite like Tor Browser itself, where access to funds or at least 'more hands on deck' becomes feasible. Or something that resembles the distributed and resilient nature of Tails, or Whonix, or Qubes teams.

Just my un-asked-for 2c :) (I would volunteer my team having been on FOSS teams before but am not asking, since Micah doesn't know me from 'Adam'.. a team needs to have some established trust)

**Comment by micahflee** [comment]
Hey @Baccount, I agree that this would be logistically very tricky. If Tor Project published cross-platform tor binaries in an easier fashion it might be more doable. I think the proper solution instead is to just make OnionShare releases more frequently, and specifically in response to Tor updates that contains vulnerabilities that affect onion services.

Note that I'm planning on making the v1.2 release any day now. I'm currently blocked by waiting for a CA to give me a valid code signing certificate for Windows, but that will hopefully be done very soon.
