### ISSUE TITLE
Proposed feature: choosing of temporary folder

### ISSUE THREAD

**Issue by NulAsh** [micahflee/onionshare#506]
I think, instead of always using the directory from tempfile.mkdtemp() which could be overfilled, user should have the option to select folder (for example on a drive with enough free space or on encrypted drive for greater security).
That's in onionshare/common.py, in class ZipWriter
you can change __init__ to
def __init__(self, zip_filename=None, processed_size_callback=None, tmpdir=None):
and a little below:
self.zip_filename = '{0:s}/onionshare_{1:s}.zip'.format(tempfile.mkdtemp(dir=tmpdir), random_string(4, 6))
and also change Settings Dialog

**Comment by Baccount** [comment]
Can you open a pull request with your proposed change so others can easily test it.
https://github.com/micahflee/onionshare/pulls

**Comment by NulAsh** [comment]
I have to learn pyqt5 to do it

**Comment by mig5** [comment]
P.S I have found from my work in #497  that if /tmp is full, Python already resorts to using /home somehow for the tmp data.

**Comment by NulAsh** [comment]
I'm using Windows. And also, there's still argument about security.

**Comment by NulAsh** [comment]
https://github.com/micahflee/onionshare/pull/522
I made a pull request. Sorry, i had not enough experience with PyQt5 before, maybe you can make it better.

**Comment by NulAsh** [comment]
Forgot about tests.

**Comment by NulAsh** [comment]
Checks passed

**Comment by micahflee** [comment]
Before adding this feature, can you explain a little more why it's necessary?

In the case where you have an encrypted external drive, but your internal drive (where your tmp data is stored) isn't encryption, the "proper" solution would be to just encrypt your internal drive -- and this would protect against many other attacks as well, including someone with physical access just adding malware to your computer, replacing the `onionshare.exe` with a malicious version, etc. But hopefully this isn't a problem for most people these days because full disk encryption is getting much better supported, and is enabled by default now in many situations.

The reason I'm hesitant to add it is because I'd like to try to keep OnionShare's UI as simple as possible, and only add new sections to the settings dialog if they're really necessary.

**Comment by NulAsh** [comment]
Do you remember about VeraCrypt hidden volumes? It's a concept where even if you forced to give password for your cryptovolume, you still have another, hidden cryptovolume, where you have the most sensitive data. But traces of temporary zip file then can be unerased.
By the way, about making it portable - you can make it even more user-friendly, just add one checkbox "Portable mode". When switch to checked, it will save options to the directory, where program is located. When unchecked, it will delete this file and save to usual appdata or ~/.config/onionshare/ directory.

**Comment by mig5** [comment]
I feel that using Tails (it ships with OnionShare already) and (if even necessary) a 'portable' json on a persistent encrypted volume or encrypted USB stick for the --config arg, would be a more robust 'zero knowledge' method that doesn't require any changes to OnionShare

It seems reasonable if a combination of plausible deniability and portability is required, 'use Tails' is a useful solution - but that's just my 2c :)

**Comment by micahflee** [comment]
Closing this and #522 for now because I don't see how it's necessary.
