### ISSUE TITLE
Backdoor in any python script 

### ISSUE THREAD

**Issue by leonardoporpora** [micahflee/onionshare#527]
Guys I read this and I’m so scared about it. https://t.co/rR4p20Y3Ls Let me know

**Comment by mig5** [comment]
I don't think OnionShare (or any other app for that matter) can effectively protect against a client-side manipulation of local python files. The same is true of any other app written in any other language.

A remote injection would be bad. A client-side compromise is game over for the user.

And the project being on Github means its source code can be audited by anyone to ensure that no malware has been planted.

The best mitigation against client-side backdoors is to compartmentalize the program so that its ability to pivot and access other data/compromise other applications is reduced. 

Look at https://qubes-os.org for a great 'security through compartmentalization' OS whereby you can run OnionShare in its own VM isolated from (say) your SSH/GPG keys or browser/mail etc, and even lock down the outbound firewall on that OnionShare VM. All my OnionShare dev work is done in such a Qubes appVM.
