### ISSUE TITLE
When I have "use Tor bundled with onionshare" enabled, clicking on check for updates gives me this error "Error checking for updates"

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#528]
When I have "use Tor bundled with onionshare" enabled, clicking on check for updates gives me this error  "Error checking for updates: Maybe you're not connected to Tor, or maybe the OnionShare website is down."

**Comment by mig5** [comment]
I reproduced only once, all other times it works for me. (It checks over the Onion Service, maybe it's just more Tor congestion nothing we can do about?)

The time that it failed for me, this was in the log

```
UpdateChecker.chec: loading http://elx57ue5uyfplgva.onion/latest-version.txt
Onion.get_tor_socks_port
UpdateCHecker.check: Socket error: timed out
```

**Comment by mig5** [comment]
The timeout is only set to 15 seconds, maybe it needs to be a bit longer during periods of congestion

**Comment by Baccount** [comment]
I think the issue is when bundle tor is selected the updates does not have any connection,  there is no delay from when I click check for updates and when I get the error message.

**Comment by mig5** [comment]
ok odd, I am using bundled Tor on OS X and I don't reproduce that at least against a built version of master branch

**Comment by mig5** [comment]
@Baccount I reproduce if I first got the 'Tor is taking too long to connect' message with Bundled Tor, and then am taken to the Settings dialog. Of course in that scenario the 'Check for updates' fails immediately since it relies on Bundled Tor to have connected.

So do you mean that your bundled Tor never connected and then you went straight to Settings Dialog and clicked 'Check for Updates'?

If so maybe we should disable the pushbutton until Tor is connected somehow..

**Comment by Baccount** [comment]
Disabling the check for updates button should work.
