### ISSUE TITLE
Navigate folders within the app's File List and the web page of a share

### ISSUE THREAD

**Issue by leonardoporpora** [micahflee/onionshare#582]
Add the possibility to look into the folder once loaded on onionshare

**Comment by mig5** [comment]
Do you mean the Onionshare app interface, or the web interface when the user views the page to download? (the latter I can see might make sense, the former the sender can already navigate their folders, they're on their computer...)

**Comment by leonardoporpora** [comment]
Both of them.

**Comment by leonardoporp** [comment]
Will this feature be implemented in the next release?

**Comment by micahflee** [comment]
No it won't, not for 2.0.

I think the best way to implement this is with static website sharing, described in #791 and #855. If you want people to be able to browse files and download individual files, you choose a folder to share as a static website, and it'll show a directory listing. In fact, I'll go ahead and close this issue because I think that issue and PR supercede it.

That feature is currently slated for version 2.1.
