### ISSUE TITLE
Add a section about what dependencies are needed

### ISSUE THREAD

**Issue by simhnna** [micahflee/onionshare#591]
Hi,

I'm packaging onionshare for Archlinux and would find it very helpful to have a page listing all hard dependencies and all optional ones.  
It's rather hard to find that out using the information that is currently provided.

* From the looks of it, you switched from depending on the tor-browser being running, to using the tor executable.
* I'm currently wondering about pysocks, which doesn't seem to be necessary yet it's still mentioned in the requirements in github.
* What is obfs4 needed for? Does it work without it?

Havind a section in the readme about that would be very helpful. Maybe also include the dependencies in the Changelog, since that is the first place I look for changes that I need to do.

**Comment by simhnna** [comment]
Oh, and I forgot about nautilus-python. It sounds like an optional dependency, right?

**Comment by mig5** [comment]
Hi @simhnna,

The dependencies for Linux are defined in the [BUILD.md](https://github.com/micahflee/onionshare/blob/develop/BUILD.md). There are many projects that use a BUILD.md for providing info for developers, whilst keeping CHANGELOG for literally what's changed per release, README for general user info, etc.

The BUILD.md currently provides explicit package names for Debian and Redhat-based distros, but it should be pretty straightforward to surmise the equivalent package names for your OS. (There's even a mention of ArchLinux in there already):

python3-flask
python3-stem
python3-qt5
python3-pytest
nautilus-python
tor
obfs4

To answer your other questions:

1) Yes, Linux systems are expected to have a system-wide installation of Tor, which OnionShare will use by default as 'bundled mode' if it's not configured to use the other methods (Tor Browser, like before, or control/socket connections to the system-wide Tor)

2) pysocks is not mentioned in the BUILD.md, so you can probably ignore it unless the other packages above drag it in as a dependency anyway (maybe Stem?) Onionshare bundles its own socksipy for various uses.

3) obfs4 is required for Bridge support in Tor. If your users supply custom bridges (via the Settings screen) that are obfs4 pluggable transports, and the obfs4 proxy is not installed, this will break their configuration. Debian and Redhat based distros package obfs4 already. For Windows and Mac we fetch the obfs4proxy binary that comes shipped with Tor Browser (they depend on it for the same reason: bridges)

4) The setup.py will add a file to /usr/share/nautilus-python/extensions/ so I don't think it's optional right now. However, there was recently a patch merged in for BSD support which I think forced it to be optional: see https://github.com/micahflee/onionshare/commit/ae494c8e331cc2c945e66c27cc53344de52e549a

I don't think we can quite make it optional the same way for subsets of Linux right now, but maybe you can patch it to not be required in your port?

I feel that the BUILD.md already satisfies the requirement for mentioning dependencies. I would not look for dependency info in a CHANGELOG.md which is just listing what bugs were closed, what features were added, etc. But I will open a PR for mentioning the dependencies in more broad detail rather than (just) specific OS package names.

There is also a section in the wiki for [Linux Distribution Support](https://github.com/micahflee/onionshare/wiki/Linux-Distribution-Support) which can go into more detail if not covered by the BUILD.md. If you can edit the wiki (there is currently some uncertainty as to whether any Github user can edit the wiki, still investigating) then I encourage you to add any extra Arch info there.

**Comment by simhnna** [comment]
thanks, I somehow didn't find `BUILD.md`...

Your elaboration covers what I need right now. I guess I'll add obfs4 as an optional dependency for now and patch out the nautilus-python extension. If someone complains I guess I'll add that as a separate build script in archlinux.

As for the wiki, I can't edit it, but you can pretty much copy the line that is in BUILD.md to the wiki.
