### ISSUE TITLE
An option to use onionshare without Tor like for local network [Feature Request]

### ISSUE THREAD

**Issue by M4rcellxD** [micahflee/onionshare#698]
or send file to friend faster for not important data

**Comment by Baccount** [comment]
This is all ready possible, the file receiver needs to type in the ip http://127.0.0.1:"plus the ra randomly generated port number" and the slugs.
Example 
run `onionshare-gui` in terminal.
and share a in the GUI file, in terminal you will see the ip and port number and you add the slugs onto the end of that string.
Here is the final url that the receiving user enters into there browser to receive the file, **BUT there is no encryption protecting the files when shared using this method** 
http://127.0.0.1:17634/lyrically-snugness

**Comment by micahflee** [comment]
You can already run `onionshare-gui --local-only` to completely skip the Tor part -- but this is only useful for development, because it only listens on 127.0.0.1 so it's not accessible from other computers on the local network.

Honestly, I think an ssh or samba service is more the way to go. Otherwise the user will be responsible for potentially complicated port forwarding stuff, and also the transfer itself won't be end-to-end encrypted because it won't be going over an onion anymore.

It's a cool idea, but I don't think it fits with this project.
