### ISSUE TITLE
When receiving a file with a long file name, the file size gets cut off in the file downloader popup

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#704]
When receiving a file with a long file name, the file size gets cut off in the file downloader popup "Upload history". Here is a photo showing the bug occur. Tested using receiver-mode-gui branch
<img width="350" alt="onionshare bug" src="https://user-images.githubusercontent.com/10781882/40681686-b408a51c-633e-11e8-991d-db567b87058b.png">

**Comment by micahflee** [comment]
This issue is almost resolved with #737, but not entirely. When you have a really short filename, it adds "[...]" to the end of it when it isn't necessary, unless you resize the window to be much wider than necessary.

For example, this full filename I'm uploading is `onionshare.tgz`, but it displays the "[...]" anyway. And that goes away when I make the window wider.

![screenshot_2018-09-17_13-12-03](https://user-images.githubusercontent.com/156128/45647735-761a9f00-ba7b-11e8-86fa-ba017aeba21f.png)

**Comment by mig5** [comment]
Yeah I noticed this last night too :( this bug is the bane of my existence..
