### ISSUE TITLE
Noscript blocks something on the Onionshare download page with TorBrowser 60 nightly

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#705]
### Update
**Even though Noscript marks the onion as untrusted, the downloading and uploading files options work correctly, so this may not be a issue.**

Noscript blocks something on the Onionshare download/receiving page when using TorBrowser 60 nightly, and the security settings set to "Safest"
<img width="930" alt="bug" src="https://user-images.githubusercontent.com/10781882/40865823-3e87ca02-65af-11e8-815e-f95ba1ab2467.png">
TorBrowser 60 nightly can be downloaded Here, and it is signed by gk's signing key here. [Key](https://db.torproject.org/fetchkey.cgi?fingerprint=35CD74C24A9B15A19E1A81A194373AA94B7C3223), Gk's key fingerprint 35CD74C24A9B15A19E1A81A194373AA94B7C3223

https://people.torproject.org/~gk/testbuilds/TorBrowser-tbb-nightly-esr60-osx64_en-US.dmg
https://people.torproject.org/~gk/testbuilds/TorBrowser-tbb-nightly-esr60-osx64_en-US.dmg.asc
@mig5 
@micahflee 
Also clicking the "!" shows TorBrowser's new circuit display :)
<img width="616" alt="bug1" src="https://user-images.githubusercontent.com/10781882/40866043-845246ec-65b0-11e8-84c2-df6da3b5084d.png">

**Comment by Baccount** [comment]
Even though Noscript mark the onion as untrusted, the downloading and uploading files work correctly, so this may not be a issue.

**Comment by mig5** [comment]
This is probably just because the web page has javascript now (sorting by size, etc).

NoScript probably just blocking the javascript element, but indeed it should just degrade gracefully, so I think this is #notabug , but I'll investigate in more detail.

**Comment by mig5** [comment]
Going to resolve this because the only Javascript in Onionshare is for sorting name/size columns. There's already a Content-Security-Policy header that limits script-src to 'self' so this is as secure as it will ever be.

NoScript is doing the right thing by detecting there's some javascript and blocking it - same as if Tor Browser's safety settings were configured to not parse any javascript. No loss of functionality except for inability to sort the table (return to original behavior).

Thanks for checking though.
