### ISSUE TITLE
When Tor is disconnected and I click "start receiving mode" the app crashes

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#707]
1. compile receiver-mode-gui branch
2. open OnionShare and set it to connect to Tor visa TorBrowser.
3. make sure it is connected and works correctly, then close tor browser and click "start receiving mode" and the app crashes every time.

**Comment by mig5** [comment]
@micahflee the problem here is that if the Tor connection is severed before 'Start Receive Mode' is clicked, the server is actually still in Share mode. It doesn't enter Receive mode until the Receive mode button is clicked.

Therefore I think we'll need something in the Share mode handle_tor_broke_custom() that also hides the Receive Mode button.. or rather, there perhaps needs to also be a 'general' function for when Tor connection is lost, not just mode-specific..

**Comment by mig5** [comment]
Nope, I was wrong about the above - still learning the refactored code in receiver-mode-gui branch.

I think I have a fix, ready at https://github.com/micahflee/onionshare/pull/718

**Comment by mig5** [comment]
#718 was merged so this can be closed.
