### ISSUE TITLE
OnionShare 1.3-1 crashes on Debian Stretch 9.4

### ISSUE THREAD

**Issue by Debby800** [micahflee/onionshare#708]
I am trying to run OnionShare 1.3-1 on Debian Stretch 9.4.
I open synaptic, and upgrade OnionShare to 1.3-1. I then run, from a terminal:
~$ onionshare-gui
```    Onionshare 1.3 | https://onionshare.org/
    process 20124: D-Bus library appears to be incorrectly set up; failed to read machine uuid: 
    Failed to open "/etc/machine-id": Permission denied. See the manual page for dbus-uuidgen to correct this issue.
    Qt: Session management error: None of the authentication protocols specified are supported
    libGL error: MESA-LOADER: failed to retrieve device information
    libGL error: Version 4 or later of flush extension not found
    libGL error: failed to load driver: i915
```
These seem to be warnings. 

The OnionShare window now asks how should Onionshare connect to Tor. When selecting: "Connect to the Tor controller", Onionshare says it succeeds, and tries to save that setting. 
Then it crashes with:
```
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/onionshare_gui/settings_dialog.py", line 669, in save_clicked
        settings.save()
      File "/usr/lib/python3/dist-packages/onionshare/settings.py", line 126, in save
        open(self.filename, 'w').write(json.dumps(self._settings))
    PermissionError: [Errno 13] Permission denied: '/home/Debby/.config/onionshare/onionshare.json'
    Aborted
```
Note that libQtgui-4 v. 4:4.8.7+dfsg-11; and: xserver-xorg-video-intel v. 2:2.99.917+git20161206-1 - are installed.
Can you suggest a way to proceed/debug?
~$ uname -a
```    Linux 4.15.0-2-amd64 #1 SMP Debian 4.15.11-1 (2018-03-20) x86_64 GNU/Linux```

**Comment by mig5** [comment]
Hi @Debby800, sorry to hear of your issue. 

Is there any chance you started Onionshare as root or other user at some stage, and it created /home/Debby/.config/onionshare/onionshare.json with the wrong ownership?

Subsequently you've opened it as Debby or another non-privileged user, and it can't save to the /home/Debby/.config/onionshare/onionshare.json file because it's owned by the other user.

See if you can 'sudo chown Debby /home/Debby/.config/onionshare/onionshare.json' in a terminal, and then try to start onionshare-gui again, and hopefully the errors have gone away.

**Comment by u451f** [comment]
I think this might rather be due to AppArmor, see #686 - but in the Debian package the AppArmor profile is not enabled by default so maybe you enabled it manually?

**Comment by mig5** [comment]
OnionShare is working fine in Debian Stretch for me, we've had no other reports of this, or any follow-up from the author as to whether it was AppArmor as above, so I'm inclined to close it for now. Thanks for the report though.
