### ISSUE TITLE
Make some new UI changes

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#780]
Here's feedback from @glenn-sorrentino: https://github.com/micahflee/onionshare/pull/770#issuecomment-423412473

>I explored using a button/toggle to open up the download history. Would love your thoughts on it.
>
>Next to the status indicators is a section for opening a panel showing the download history.
>
>![toggle close](https://user-images.githubusercontent.com/28545431/45860782-ec3e3080-bd1d-11e8-8914-c3da311adf1b.png)
>
>The empty state looks a bit more like the empty state for uploading
>
>![toggle open - no downloads](https://user-images.githubusercontent.com/28545431/45860781-ec3e3080-bd1d-11e8-9726-eeeecc5dcd87.png)
>
>When a new download happens with the panel closed, an indicator is displayed over the icon.
>
>![toggle closed - indicator](https://user-images.githubusercontent.com/28545431/45860987-088e9d00-bd1f-11e8-9e73-77c113d3dcbd.png)
>
>Opening it clears the count on the toggle and shows all past and current downloads
>
>![toggle open - download history](https://user-images.githubusercontent.com/28545431/45860779-ec3e3080-bd1d-11e8-9ad4-f749c5ea1f5a.png)

I really like the new empty state look, and we should definitely implement that.

I also really like the look of the "clear all" link, and the download count.

If we do add toggling showing and hiding, I like the status indicator with a number in it. But I'm not entirely convinced we should allow toggling... besides it just probably being tricky to implement correctly, I kind of think the upload/download progress is really the important information once you've already started a share and have sent someone the address, so I'm not sure that it's useful to allow people to hide it. But maybe I'm just anticipating weird window resizing bugs that I don't want to deal with... :)

**Comment by mig5** [comment]
When we had the toggle button, there *was* a resizing issue (hiding the download/upload history area then 'stretched' the left side to fill the gap.

If we can adjustSize() back to the smaller screen, I think that would be a big win. The 'original' interface is much simpler and so I can see benefit in keeping it possible. Maybe only 'advanced' or curious users will want to see the extra detail from within the app (many users probably don't care about the Download progress bar/meta info, and maybe in Receive mode, people will just go straight to the OnionShare folder in their file browser).

So I guess I'm pro-toggle, I'm happy to see if we can get it to work at least. If too much trouble, maybe not.

Finally, I realised another challenge in Glenn's design above. The 'Download' history currently doesn't show the individual files downloaded, or their times. This is especially because a grouping of files is zipped, so only 'one' file is downloaded or in the process of being downloaded. That might be hard to demonstrate in the UI as individual file downloads, even though I like how it looks above.
