### ISSUE TITLE
"Stop sharing after first download" seems to not work in 2.0.dev

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#787]
Using v3 onion services, make sure "Stop sharing after first download" is checked. Then share something, and download it. The server stays open. This must have been a regression bug probably after the refactor of web?

**Comment by mig5** [comment]
It's funny because one of my unit tests actually tests that the server is stopped, and it passes! So I was thinking 'wtf, how can that be the case'.

So that led me to realise that the share *does* stop but the UI is not reflecting it, so it's going to be a pipes/socket thing in the GUI I think.

If you refresh the .onion after downloading the share, you can't connect (well I can't).

It also makes it clear that the test I wrote needs to be updated so that it actually tests the text of the server status bar. Checking the internal 'status' of the server (and even connecting to the web server) is not enough.

**Comment by mig5** [comment]
It works as expected via CLI too.

In the GUI, I think it holds the .onion address 'open' (it doesn't fire OnionShare.cleanup()) but it shuts down the Flask web server somehow, and somehow the server status is 0 ('stopped') or else my unit test would fail.

**Comment by mig5** [comment]
(Re: the unit tests, actually realised my tests *do* check that the server status string says 'closing automatically', and it *does* stop automatically - in other words, when run in local mode, it somehow doesn't trip this bug..). Anyway. Fix is at #788

**Comment by micahflee** [comment]
Awesome thank you
