### ISSUE TITLE
Enable Enhanced Runtime Protections for macOS 10.14

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#794]
### Apple announced that macOS 10.14 has a new Hardened runtime feature that should improve Onionshare protection against exploits.

To enable this from Terminal just run the following command, Substitute 'Developer ID' for your Developer Apple ID 
`codesign --sign “Developer ID” --options runtime WatchGrassGrow.app` _Source_ [Presentation Slides](https://devstreaming-cdn.apple.com/videos/wwdc/2018/702zi9t7twhu9310kz5/702/702_your_apps_and_the_future_of_macos_security.pdf?dl=1)

**Apple made a video that explains these new security features.** 

https://developer.apple.com/videos/play/wwdc2018-702/?time=1290
> This link takes you to the exact part of the video where he talks about the Hardened runtime.

Information on security for macOS
https://developer.apple.com/documentation/security
@mig5

**Comment by micahflee** [comment]
Hmm, this is a new feature in the macOS 10.14 SDK, however the build machine runs macOS 10.9 in order to support earlier versions of macOS. So this might not work... (But it may be possible to do something like use PyInstaller to compile the app in 10.9, but then codesign in 10.14?)

**Comment by mig5** [comment]
Would it break compatibility with older-than-macOS 10.14? We seem to get users on older Mac versions like 10.12 that see other things break from time to time (#927)

**Comment by micahflee** [comment]
Actually the build machine is running macOS 10.11.6 -- so 10.11 is the earliest version we support. But I just tested, when I try running `codesign` with `--options runtime` I get the error:

> invalid argument "runtime"

In order to add this option during codesigning, the build machine needs to be running 10.14 I believe. I could maybe do this, but I'll have to change the build process to something like this:

- Install macOS 10.14 on the build machine
- Install a macOS 10.11.6 VM
- Run the first part of `build_osx.sh` (without the `--release`) in the VM
- Run only the `--release` part, which does the codesigning, on the host machine

I _think_ this will work -- I'll still want to try running the final binary on a 10.11.6 machine to make sure it works, but I expect it would.

Because this is a lot, I'm going to remove the 2.1 milestone and focus on this a bit later.

**Comment by micahflee** [comment]
Extended support for macOS 10.12 ends September 2019, next month. So I think maybe the build machine should now be based on macOS 10.13 -- which still doesn't have support for Enhanced Runtime Protections, but with time this problem will hopefully go away, once we can require 10.14+ for OnionShare.
