### ISSUE TITLE
make tor startup timeout configurable

### ISSUE THREAD

**Issue by weaselp** [micahflee/onionshare#832]
Onionshare currently gives Tor 120 seconds to bootstrap (150 with bridges, iirc).

Sometimes that's too little time.

Please make this configurable.

**Comment by micahflee** [comment]
Instead of making it configurable, would it help to just increase the timeouts? I like to avoid cluttering the settings dialog with options that many users won't understand, and if the default timeout is too short, it should probably be increased for everyone.

How many seconds do you think should always be enough time? We could do 180 seconds in all cases, or 180 seconds without bridges, 210 seconds with bridges?

**Comment by mig5** [comment]
Perhaps it could be a CLI only flag to override the default timeout, for advanced users? (And not shown in the settings dialog, nor even saved to the settings .json)

The use case of being able to configure the timeout is something that suits some sort of automated use of the tool (in order to avoid false positive failures in tests/builds for example). It's likely the sort of user doing that, is using the CLI version already, so this could be a good middle-ground of giving a useful flag for an advanced user while keeping it as-is for everyday GUI/CLI use.

From memory @weaselp is using OnionShare in such a programatic way (see #816 )

**Comment by micahflee** [comment]
That's a good idea @mig5, I'm fine with making this a CLI-only option.

**Comment by iology** [comment]
version 2.0

I hope the limit can be at least as high as the TorBrowser's (using meek; does meek_lite take more time?). My progress always stops at "50% Loading relay descriptors for internal paths". It seems very likely to succeed if given more time and hopefully there be an option for tinkering.

I can observe that OnionShare makes several separate connections to the Azure server sequentially during the whole setup process, while the TorBrowser uses only one. Does it matter for the total time?

**Comment by micahflee** [comment]
The reason why OnionShare acts differently (and takes longer to connect to Tor, or even stalls sometimes) than Tor Browser might be related this.

With Tor Browser, the `DataDirectory` is in a static location, and it saves a cache of information related to the Tor network. The first time you connect, with a brand new Tor Browser, it takes the longest because it has to do many more lookups. But then in the future when you open Tor Browser, it connects to the network much faster because it uses its cached data.

But with OnionShare, each time you connect it uses a new temporary directory for the `DataDirectory`, which means it starts over from scratch each time and doesn't have the benefit of the cache. It's basically like opening Tor Browser for the first time, only it happens each time you open OnionShare.

So I'm not sure, but I imagine it's probably related to this. We could make OnionShare have a static `DataDirectory` that never changes, and that will make connecting to Tor quicker and more reliable. But at the moment, you can actually open multiple OnionShare processes at once, and each process runs its own tor subprocess, and I'm worried that if someone does this, and multiple tor subprocesses share the same `DataDirectory`, chaos will ensue.

**Comment by iology** [comment]
If the problem is simply due to the slow network communication (for me it's often due to QoS), OnionShare can indicate that and ask whether the user want to continue as well, instead of immediately stopping the startup process. TorBrowser does not provide any timeout option on the UI either but it seems the send/recv speed is considered.

About sharing DataDirectory, is it possible to back it up right after fetching it, then use it for new instances of OnionShare (which can make a new backup again)?

**Comment by mig5** [comment]
Right now it creates a separate randomised tmp directory each time it connects.

Note that in the settings dialog, you can switch from 'bundled' mode to a system-provided Tor, or Tor Browser in the background, to avoid this problem altogether (instead relying on those other Tor's cache/state).

There is an ancient PR for making the tor cache/state data persistent - help would be appreciated https://github.com/micahflee/onionshare/pull/551

**Comment by iology** [comment]
> Note that in the settings dialog, you can switch from 'bundled' mode to a system-provided Tor, or Tor Browser in the background, to avoid this problem altogether (instead relying on those other Tor's cache/state).

Ah, yes it works. I have successfully sent and received files. Previously I thought there was some bug about sharing the tor program of TorBrower that made it stuck at "Starting" and I wanted to prepare a bug report. Now I see it is probably due to the unstable network & preemption.
