### ISSUE TITLE
CVE-2018-19960

### ISSUE THREAD

**Issue by u451f** [micahflee/onionshare#837]
Hi!

Onionshare received a CVE: https://security-tracker.debian.org/tracker/CVE-2018-19960

The debug_mode function in web/web.py in OnionShare through 1.3.1, when --debug is enabled, uses the /tmp/onionshare_server.log pathname for logging, which might allow local users to overwrite files or obtain sensitive information by using this pathname.

I'd want to update the Debian package asap, would you be able to provide a fix to the above mentioned issue?

**Comment by micahflee** [comment]
I think it's worthwhile putting this debug file somewhere other than `/tmp`. However I don't actually understand how this could be considered a vulnerability.

If OnionShare is run with debug mode on (which isn't default), and if the OnionShare recipient somehow triggers a separate bug that causes flask to throw an exception, then the stacktrace for this exception gets written to this debug file. It never even includes sensitive information like the filenames of files being shared. (Most debug information, some of which does include sensitive information, is written to stdout, not to disk.) Additionally, an attacker having access to the local filesystem is outside the scope of OnionShare's [threat model](https://github.com/micahflee/onionshare/wiki/Security-Design) because we assume that the endpoint hasn't been compromised. If this is a vulnerability, a much more serious Debian vulnerability is the fact that user homedirs are world-readable by default, so this same attacker can access the private data of every user.

But that said, I'll make a hotfix and a 1.3.2 release, which disables saving a flask debug log at all for 1.3.x (it hasn't actually been necessary for debugging in quite some time). And I'll make a separate branch to merge into develop for 2.x.

**Comment by micahflee** [comment]
Version 1.3.2 has been released! There is a signed git tag.

**Comment by u451f** [comment]
I've asked the security team about their thoughts to qualify this as a security issue and received this reply: "Debian uses kernel hardening on Linux by default which renders this non-exploitable (and the release notes state that if rolls a custom kernel the same options need to be enabled). The only remaining impact is that on a multi user environment one user using the debug mode prevents others from using debug mode, but that's mostly a bug, not a security issue."

Cheers & thanks again for your prompt reaction :)
