### ISSUE TITLE
Windows sees 2.0.dev.2 install as malware

### ISSUE THREAD

**Issue by Sharpiro** [micahflee/onionshare#862]
I downloaded the [2.0.dev.2](https://github.com/micahflee/onionshare/releases/download/v2.0.dev2/onionshare-2.0.dev2-setup.exe) and windows immediately blocked me from opening it, until I told it to ignore.

However, once I installed the software, Windows Defender shows the install as containing a Trojan and will continue notifying you until it is removed.

The second time I went through it while collecting screenshots, Windows actually auto-removed "onionshare-gui.exe"!

![1](https://user-images.githubusercontent.com/9012043/50554227-06749c80-0c85-11e9-8888-5989e9a7a1b0.png)
![2](https://user-images.githubusercontent.com/9012043/50554228-070d3300-0c85-11e9-811f-e206684e4f72.png)
![3](https://user-images.githubusercontent.com/9012043/50554229-070d3300-0c85-11e9-9555-5644d59a5f2e.png)
![4](https://user-images.githubusercontent.com/9012043/50554230-070d3300-0c85-11e9-8b3c-be85098d6fdc.png)

**Comment by micahflee** [comment]
This isn't good, I'm looking into it! I suspect that the virus definition is something PyInstaller-related, like possibly python malware uses the same tech OnionShare uses to build the .exe.

**Comment by micahflee** [comment]
VirusTotal [isn't happy](https://www.virustotal.com/#/file/d75c27dd6c721ef28ad5e374b9ebf4957413c689570f7bfded3ec835fb01e3cc/detection) with the installer either.

![screen shot 2019-01-16 at 12 31 34 pm](https://user-images.githubusercontent.com/156128/51276838-b4bd5900-198a-11e9-8f1e-3cd6e2c5123b.png)

I'm going to rebuild the Windows 10 build machine from scratch and make another release and see if VirusTotal still flags that new release.

**Comment by micahflee** [comment]
I'm pretty sure this is PyInstaller. There are several other cases of PyInstaller-related false positives:

- https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg
- https://github.com/pyinstaller/pyinstaller/issues/603
- https://github.com/pyinstaller/pyinstaller/issues/2988

The advice on stackoverflow is to compile your own PyInstaller bootloader (https://pythonhosted.org/PyInstaller/bootloader-building.html) for Windows, and also to report false positives to anti-virus vendors.

Using a freshly built Windows 10 build machine, I made a release of GPG Sync (a similar python/Qt5/PyInstaller project), and the several AV programs flagged it as a virus as well. I'm about to try again with OnionShare, but I suspect this is what the problem is.

**Comment by micahflee** [comment]
Wow, yeah. I'm making a OnionShare `2.0.dev3` release right now, and this is what VirusTotal thinks about the freshly-built `onionshare-gui.exe`, from a freshly-built, fully updated VM, with nothing installed except the build tools and dependencies:

<img width="1096" alt="screen shot 2019-01-25 at 3 06 59 pm" src="https://user-images.githubusercontent.com/156128/51777680-f2b92c00-20b2-11e9-826e-c64f73207f58.png">

I'm going to compile my own PyInstaller bootloader and try again, but I don't have time at the moment.

**Comment by micahflee** [comment]
That's more like it.

<img width="1126" alt="screen shot 2019-01-26 at 10 47 44 pm" src="https://user-images.githubusercontent.com/156128/51797701-5b8ccb00-21bd-11e9-9d7e-6079195068fc.png">

**Comment by micahflee** [comment]
Ok, I just uploaded a new release, OnionShare 2.0.dev3, which does not have this problem:
https://github.com/micahflee/onionshare/releases/tag/v2.0.dev3

**Comment by Sharpiro** [comment]
nice, I just tried to install again, and Windows Defender didn't make a peep.  Nice work.  

Though when double clicking the executable to install, I did still get the smartscreen filter blue screen.  But after the install, no problem.
