### ISSUE TITLE
Change "upload" and "download" language and icons

### ISSUE THREAD

**Issue by micahflee** [micahflee/onionshare#868]
Right now, the upload and download language and icons are confusing.

In share mode, the show history icon is a down arrow, and when you click it it shows a big down arrow and says, "No Downloads Yet". When at least one person has downloaded the files, it says "Download History" at the top and "Download Started [date]" next to each time someone downloaded it. For receive mode, the show history icon is an up arrow, before anyone uploads anything it says, "No Uploads Yet", and when there are uploads it says "Upload History" and "Uploaded [date]" by each upload.

In share mode, you're sending files from your computer to somewhere else, so the arrow should be up. And in receive mode, you're getting new files onto your computer, so the arrow should be down. The words "download" and "upload" are basically reversed in OnionShare -- it's using the terms for the Tor Browser user, rather than for the OnionShare user.

Instead, share mode:

- Should use up arrows, because files are leaving your computer
- Should say "No Files Sent Yet" instead of "No Downloads Yet"
- Should say "History" instead of "Download History"
- Should say "Started sending [date]" instead of "Started Downloading [date]"

And receive mode:

- Should use down arrows, because files are coming into your computer
- Should say "No Files Received Yet" instead of "No Uploads Yet"
- Should say "History" instead of "Upload History"
- Should say "Received [date]" instead of "Uploaded [date]"

After making these changes, translators will have to update the translations for these strings before making the 2.0 release.

**Comment by glenn-sorrentino** [comment]
Here's a pass at the sharing language:


Message Name | Before | After
-- | -- | --
closing_automatically | Stopped because download finished | Sharing successfully complete
timeout_download_still_running | Waiting for download to complete | Sharing in progress
systray_download_started_title | OnionShare Download Started | Sharing Started
systray_download_started_message | A user started downloading your files | Someone is receiving your files
systray_download_completed_title | OnionShare Download Finished | Sharing Complete
systray_download_completed_message | The user finished downloading your files | Your files have been received
systray_download_canceled_title | OnionShare Download Canceled | Sharing Canceled
systray_download_canceled_message | The user canceled the download | Someone canceled receiving your files
help_stay_open | Keep sharing after first download | Keep sharing after files have been received
gui_settings_close_after_first_download_option | Stop sharing after first download | Stop sharing after files have been received
systray_download_page_loaded_message | A user loaded the download page | OnionShare address loaded

**Comment by glenn-sorrentino** [comment]
Here's a pass at the receiving language:


Message Name | Before | After
-- | -- | --
timeout_upload_still_running | Waiting for upload to complete | Receiving in progress
systray_upload_started_title | OnionShare Upload Started | Receiving Started
systray_upload_started_message | A user started uploading files to your computer | Someone is sharing files to your computer
info_in_progress_uploads_tooltip | {} upload(s) in progress | {} file(s) being shared
info_completed_uploads_tooltip | {} upload(s) completed | {} file(s) received
systray_upload_page_loaded_message | A user loaded the upload page | OnionShare address loaded
