### ISSUE TITLE
'Repeatable crash' Clicking Help in the menu dropdown causes OnionShare to crash

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#912]
Clicking "Help" in the menu dropdown causes OnionShare to crash. Tested on Onionshare 2 Stable build.
![screen shot 2019-02-19 at 11 34 31 pm](https://user-images.githubusercontent.com/10781882/53074210-fe73f480-349e-11e9-89a1-8e5ef867f1c6.png)

```
Traceback (most recent call last):
  File "onionshare_gui/settings_dialog.py", line 918, in help_clicked
AttributeError: 'bool' object has no attribute 'common'
Abort trap: 6
```
@mig5

**Comment by mig5** [comment]
@Baccount thanks!

This is a weird one because I fixed it already once before, but somehow the change has been lost/reverted.

@micahflee: this was fixed in https://github.com/micahflee/onionshare/pull/742 but the change has disappeared in develop branch. The same fix still works, so you could add that back in..
