### ISSUE TITLE
Support slightly old linux versions

### ISSUE THREAD

**Issue by ascsoft** [micahflee/onionshare#918]
Failed when I'm trying to install deb in Ubuntu 16.04 with message:
Package 'python3-distutils' has no installation candidate

**Comment by mig5** [comment]
I think you'll need to upgrade to 18.04.

https://github.com/micahflee/onionshare/issues/715
https://github.com/micahflee/onionshare/pull/854

**Comment by mig5** [comment]
Actually I see Micah's removed that dependency, but only after the 2.0 release. So probably the next release will work on older Ubuntu.

You can of course build from source on Linux (see the BUILD.md) - including making and installing your own .deb package - and then it should work for you.

https://github.com/micahflee/onionshare/commit/1e7f1c3b8895c9c1330ef731f603ad8578711f34

**Comment by danmcne** [comment]
Still have this problem.

**Comment by micahflee** [comment]
I'm using this issue to add support to slightly older versions of linux, specifically:

- Ubuntu 16.04
- Debian stretch

**Comment by micahflee** [comment]
I'm working in this branch: https://github.com/micahflee/onionshare/tree/918_old_linux

In Ubuntu 16.04, when I run `./install/build_deb.sh`, as part of the build process it tries running the tests, however by default this includes GUI tests, which pop up a million windows and takes forever, and also many of them fail. (I'm ok with GUI tests failing on old operating systems, because it's most likely due to old versions of pytest/pytest-qt, so long as they pass on more modern OSes.)

In Debian stretch, when I run `./install/build_deb.sh`, it only runs the CLI tests, like it should, and these all pass, and it successfully creates a `.deb`. I think this branch works fine in Debian stretch.

The problem is `python3-pytest` in Ubuntu 16.04 is version 2.8.7, but in Debian stretch it's version 3.0.6. The way that we're skipping tests is a new feature as of version 2.9: https://docs.pytest.org/en/latest/skipping.html
