### ISSUE TITLE
OnionShare 2 crashes on Mac OS X Yosemite 10.10.5, Intel

### ISSUE THREAD

**Issue by mukasam** [micahflee/onionshare#923]
Whether I start OnionShare 2 with Tor Browser running or not running, OnionShare 2 instantly crashes on startup. OnionShare 2 icon briefly appears for less than 1 second in the Dock, but then it disappears when OnionShare 2 crashes.  
    
First-time OnionShare user.
Advanced Tor Browser user.
    
Platform:
iMac (24-inch, Mid 2007)
Mac OS X Yosemite 10.10.5
Intel Core 2 Duo

**Comment by micahflee** [comment]
Can you open a terminal and run:

```sh
/Applications/OnionShare.app/Contents/MacOS/onionshare-gui --debug
```

This will try running OnionShare, but in debug mode so it will output everything it's doing in the terminal. Then when it crashes, can you copy and paste the debug output here?

**Comment by mukasam** [comment]
Last login: Sun Feb 24 07:41:20 on ttys000
**-iMac:~ **$ /Applications/OnionShare.app/Contents/MacOS/onionshare-gui --debug
Traceback (most recent call last):
  File "onionshare-pyinstaller", line 34, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "onionshare_gui/__init__.py", line 26, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "onionshare_gui/widgets.py", line 20, in <module>
ImportError: dlopen(/Applications/OnionShare.app/Contents/MacOS/PyQt5/QtCore.so, 2): Symbol not found: __os_log_default
  Referenced from: /Applications/OnionShare.app/Contents/MacOS/PyQt5/../QtCore (which was built for Mac OS X 10.11)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/OnionShare.app/Contents/MacOS/PyQt5/../QtCore
[940] Failed to execute script onionshare-pyinstaller
**-iMac:~ **$

**Comment by micahflee** [comment]
Ahh, I should have noticed earlier. OnionShare only works with macOS 10.11 (El Capitan) or newer. 

Apple itself only officially supports the last 3 versions of macOS, which means even 10.11 is no longer supported, so it's a good idea to upgrade at least to 10.12, but I would recommend to the latest version, 10.14.

**Comment by mukasam** [comment]
Due to limitations of my machine, I cannot upgrade the operating system. I will have to uninstall OnionShare 2. The OnionShare-2.pkg does not seem to include an uninstaller. The OnionShare wiki: https://github.com/micahflee/onionshare/wiki seems to have no uninstall instructions. Can you provide me with full instructions to completely uninstall OnionShare 2 and all related files OnionShare-2.pkg installed during the installation process. Thanks

**Comment by micahflee** [comment]
Just delete `/Applications/OnionShare.app` and it will uninstall OnionShare. If you haven't opened it without it crashing, that's all you should need to delete. If you have opened it, it will put a config file in `~/Library/Containers/com.micahflee.onionshare` which you can delete.

And actually, although the installer doesn't support macOS 10.10, you can probably get OnionShare working fine by building it from source and making your own package: https://github.com/micahflee/onionshare/blob/develop/BUILD.md#mac-os-x

There's an issue with PyInstaller, the software we use to make .app bundles, where the resulting app bundle will only work on the version of macOS you built it on or newer. The OnionShare build machine runs macOS 10.11. If you build it yourself on 10.10, your binary should work on 10.10.

**Comment by mukasam** [comment]
Great...thank you very much for the tutorial.

**Comment by pahakalle** [comment]
I have not tested this, but you could also install OnionShare with **homebrew cask** and always upgrade it with the  `brew cask reinstall onionshare` command. 
(I'm not sure if `brew cask upgrade` would also work)

**Comment by mukasam** [comment]
I appreciate your helpful input. Thank you

**Comment by quasar1970** [comment]
Tor 8.0.9 in MacOs 10.11.6
OnionShare 2.1:
Traceback (most recent call last):
  File "onionshare-pyinstaller", line 34, in <module>
  File "/Users/user/code/onionshare/venv/lib/python3.7/site-packages/PyInstaller-3.4-py3.7.egg/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "onionshare_gui/__init__.py", line 26, in <module>
  File "/Users/user/code/onionshare/venv/lib/python3.7/site-packages/PyInstaller-3.4-py3.7.egg/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "onionshare_gui/widgets.py", line 20, in <module>
ImportError: dlopen(/Applications/OnionShare.app/Contents/MacOS/PyQt5/QtCore.so, 2): Symbol not found: __os_activity_create
  Referenced from: /Applications/OnionShare.app/Contents/MacOS/PyQt5/../QtCore (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/OnionShare.app/Contents/MacOS/PyQt5/../QtCore
[464] Failed to execute script onionshare-pyinstaller

It seems that it doesn't run with MacOS 10.11.6 either. _Should warn on the installer_.
Homebrew does it:
"Warning: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this old version."
Also:
"gettext is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD gettext library & some software gets confused if both are in the library path.

If you need to have gettext first in your PATH run:
  echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile

For compilers to find gettext you may need to set:
  export LDFLAGS="-L/usr/local/opt/gettext/lib"
  export CPPFLAGS="-I/usr/local/opt/gettext/include" "

I erased OnionShare from Applications, erased ``~/Library/Containers/com.micahflee.onionshare`` and installed again with ``brew cask install onionshare`` and the same happens: OnionShare appears 1 or 2 seconds in the Dock and disappear.
