### ISSUE TITLE
The problem with the fall of the program after downloading files Windows 7 32, 64

### ISSUE THREAD

**Issue by shveicar** [micahflee/onionshare#945]
Hi, after installing the program, I give her a file to send After downloading the file via a link (verified using new and old addresses, run a onionshare-gui.exe), the program crashes with the appearance of such a window: https://s17.directupload.net/images/190318/576dihpz.jpg 
![scrin](https://user-images.githubusercontent.com/5096776/54524962-dbdcda80-497b-11e9-9552-b4b1ac8c1327.jpg)

I used Russian interface (although am confident that the problem not in this).
a similar crash occurred while checking this version - onionshare-2-setup.exe on other computers. After falling Tor server continues to work, it can be seen in the task Manager (process tor.exe).
I hope that this is a solvable problem because this program can help many people in the free dissemination of information. Thanks.

**Comment by shveicar** [comment]
I also tested this version on Windows 10 enterprise 2016 ltsb x86. 
there is no such error but the program just closes, although in the settings unchecked option -  (Stop sharing after files been sent)
![scrin1](https://user-images.githubusercontent.com/5096776/54524893-ae902c80-497b-11e9-8651-128a5e49a245.jpg)

**Comment by micahflee** [comment]
This could be tricky to debug. @shveicar that error you see basically just means "OnionShare crashed" but it doesn't give any details. To get the details we normally run OnionShare in debug mode, but that doesn't actually work in Windows (because debug mode prints output to the console, and `onionshare-gui.exe` does not have a console when run, so it's not easy to see the output).
