### ISSUE TITLE
On updating built-in tor in Debian like distributions

### ISSUE THREAD

**Issue by u451f** [micahflee/onionshare#949]
For Debian like distributions (Debian, Tails, Ubuntu) I am strongly wondering about continuing to ship the built-in tor because it requires to update the Onionshare packages fast, in time when a new tor is released, if a serious bug in tor is discovered etc.

How do you think we should handle this issue? Would it be possible to strip the built-in tor from the Linux version (where  people can use system tor super easily)?
Open question, I am not considering doing that for the next Debian upload (currently working on it!), but it's a serious question that we should discuss IMO.

**Comment by micahflee** [comment]
The "Use the Tor version built into OnionShare" just means OnionShare launches its own `tor` subprocess as the user running onionshare, with it's own custom `torrc`. In Windows and Mac, we bundle a copy of the `tor` binary and associated files (extracted from Tor Browser, shortly before the onionshare release, which totally could get out-of-date) with the onionshare package.

But in Debian (and other Linux distros), `tor` is a package dependency, and using the default bundled Tor setting will run `/usr/bin/tor` in a subprocess, so it will always run whatever version you install from the repos, and it won't interfere with any system tor you might already have. (This also has a downside: if you're running onionshare in a Linux distro with an old `tor` package in the repos, like if you don't add the official TPO repo, then you end up using an old version tor, and new features like v3 onion services might not work.)

So I could be misunderstanding something, but I don't think this is actually a problem.

It would be cool to make it use the system tor automatically without having to launch its own subprocess, but there are a number of problems with that. The main one is that the default `torrc` doesn't have the control port open, and unprivileged users aren't part of the `debian-tor` group so they don't have permission to connect to the `/var/run/tor/control` socket file, so the user has to manually change a bunch of settings (basically follow [these instructions](https://github.com/micahflee/onionshare/wiki/Connecting-to-Tor#using-a-system-tor-in-linux)) in order to have onionshare work. And also, maybe the user could change settings in their system tor's `torrc` that would break stuff, make it so onionshare doens't know how to connect to the controller anymore, etc., or they could disable the tor systemd service so it might not be available when the user opens onionshare.

**Comment by micahflee** [comment]
Closing this issue, but feel free to re-open if I'm wrong

**Comment by u451f** [comment]
Thanks a lot for those explanations! Much appreciated.
